In [ ]:
def answer_one():
    # Working till replacing "..." with NaN

    import numpy as np
    import pandas as pd
    import re
    energy=pd.read_excel('Energy Indicators.xls',skiprows=17,skipfooter=38)
    del energy['Unnamed: 0']
    del energy['Unnamed: 1']
    energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy['Energy Supply']=energy['Energy Supply']*1000000           #converting peta joules to Gigi joules (1P=1,000,000GJ)
    energy = energy.replace("...",np.NaN)
    energy = energy.replace('........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',np.NaN)
    # Regex for corecting names with bracket
    country_list= []          # list  for storring corrected names of countries
    for i in energy['Country']:
        pattern = re.compile(r'\D+')
        Country1 = pattern.findall(i)
        newdata =''.join(Country1)
        loc = newdata.find('(')
        if loc >0:
            newdata = newdata[0:loc-1]
        else:
            newdata = newdata
        country_list.append(newdata.strip())

        
        
    energy['Country']=country_list        # Replacing old column (Country) with correct name of countries in our list_country

    energy.set_index('Country',inplace=True) 

    country_name = {"Republic of Korea": "South Korea","United States of America": "United States","United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"}
    energy.rename(index = country_name,inplace = True)

    
    # 3)loading the GDP data from the world bank csv file

    GDP=pd.read_csv('world_bank.csv', skiprows=4,skipfooter=0)
    GDP.set_index('Country Name',inplace=True)

    country2={"Korea, Rep.": "South Korea", 
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"}

    GDP.rename(index = country2,inplace = True) 
#     print(len(GDP.columns))
    GDP
    
    
    
    # 4a) load the Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology from the file scimagojr-3.xlsx, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame ScimEn.

    ScimEn=pd.read_excel("scimagojr-3.xlsx",skiprows=0,skipfooter=0)
    ScimEn

    # 4b) only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).

    ScimEn2=ScimEn[0:15]
#     print(len(ScimEn2.columns))
    ScimEn2

    # 5) 

    # Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). 
    #     Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).

    # The index of this DataFrame should be the name of the country, and the columns should be 
    # ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index',
    #  'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', 
    #  '2012', '2013', '2014', '2015'].

    df_GDP_ScimEn=pd.merge(ScimEn2, GDP,how ='inner', on=None, left_on='Country', left_index=False, right_index=True, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)
#     print(len(df_GDP_ScimEn.columns))
    df_GDP_ScimEn
    
    #6

    df_GDP_ScimEn_Energy=pd.merge(df_GDP_ScimEn,energy,how ='inner',left_on='Country',   left_index=False, right_index=True, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)
#     print(len(df_GDP_ScimEn_Energy.columns))
    # df_GDP_ScimEn_Energy=pd.merge(energy,df_GDP_ScimEn,how ='right', on='Country',  left_index=False, right_index=True, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)
    df_GDP_ScimEn_Energy

    df=df_GDP_ScimEn_Energy[['Country','Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
           'Citations per document', 'H index', 'Energy Supply',
           'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
           '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
#     print(len(df.columns))
    df.set_index('Country',inplace=True)
    df
    
    
    
    return df

answer_one().shape

In [ ]:
import pandas as pd
import numpy as np
import re

#2 reading and cleaning energy df

energy=pd.read_excel('Energy Indicators.xls',skiprows=17,skipfooter=38)
del energy['Unnamed: 0']
del energy['Unnamed: 1']
energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy['Energy Supply']=energy['Energy Supply']*1000000           #converting peta joules to Gigi joules (1P=1,000,000GJ)
energy = energy.replace("...",np.NaN)
energy = energy.replace('........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',np.NaN)
# Regex for corecting names with bracket
country_list= []          # list  for storring corrected names of countries
for i in energy['Country']:
    pattern = re.compile(r'\D+')
    Country1 = pattern.findall(i)
    newdata =''.join(Country1)
    loc = newdata.find('(')
    if loc >0:
        newdata = newdata[0:loc-1]
    else:
        newdata = newdata
    country_list.append(newdata.strip())



energy['Country']=country_list        # Replacing old column (Country) with correct name of countries in our list_country

energy.set_index('Country',inplace=True) 

country_name = {"Republic of Korea": "South Korea","United States of America": "United States","United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"}
energy.rename(index = country_name,inplace = True)






# 3)loading the GDP data from the world bank csv file

GDP=pd.read_csv('world_bank.csv', skiprows=4,skipfooter=0)
GDP.set_index('Country Name',inplace=True)

country2={"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"}

GDP.rename(index = country2,inplace = True) 
#     print(len(GDP.columns))
GDP

# 4a) load the Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology from the file scimagojr-3.xlsx, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame ScimEn.

ScimEn=pd.read_excel("scimagojr-3.xlsx",skiprows=0,skipfooter=0)
# ScimEn
ScimEn2=ScimEn[0:15]
#     print(len(ScimEn2.columns))
    ScimEn2
    
GDP.head()

In [ ]:
(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer')).shape
# union =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer'),GDP,left_on='Country',right_index=True,how ='outer')
# pd.merge(ScimEn2,energy,left_on='Country',right_index=True,how ='inner')
# union.shape

In [ ]:
union =  pd.merge(pd.merge(ScimEn2,energy,left_on='Country',right_index=True,how ='outer'),GDP,left_on='Country',right_index=True,how ='outer')
union
intersection =  pd.merge(pd.merge(ScimEn2,energy,left_on='Country',right_index=True,how ='inner'),GDP,left_on='Country',right_index=True,how ='inner')
intersection

In [ ]:
len(intersection)

In [ ]:
intersection.shape

In [ ]:
union.shape

In [ ]:
len(union)-len(intersection)

In [ ]:
len(union)

In [ ]:
union =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer'),GDP,left_on='Country',right_index=True,how ='outer')
GDP.shape

In [ ]:
(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer')).shape

In [ ]:
print("ScimEn shape= ",ScimEn.shape)
print("energy shape= ",energy.shape)
print("GDP shape= ",GDP.shape)

In [13]:

# # Assignment 3 - More Pandas
# All questions are weighted the same in this assignment. This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

# ### Question 1 (20%)
# Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.
# 
# Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:
# 
# `['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`
# 
# Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values.
# 
# Rename the following list of countries (for use in later questions):
# 
# ```"Republic of Korea": "South Korea",
# "United States of America": "United States",
# "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
# "China, Hong Kong Special Administrative Region": "Hong Kong"```
# 
# There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, e.g. `'Bolivia (Plurinational State of)'` should be `'Bolivia'`.
# 
# <br>
# 
# Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 
# 
# Make sure to skip the header, and rename the following list of countries:
# 
# ```"Korea, Rep.": "South Korea", 
# "Iran, Islamic Rep.": "Iran",
# "Hong Kong SAR, China": "Hong Kong"```
# 
# <br>
# 
# Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.
# 
# Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 
# 
# The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
#        'Citations per document', 'H index', 'Energy Supply',
#        'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
#        '2009', '2010', '2011', '2012', '2013', '2014', '2015'].
# 
# *This function should return a DataFrame with 20 columns and 15 entries.*
import pandas as pd
import numpy as np
import re
def answer_one():
    energy = pd.read_excel(r'Energy Indicators.xls')
    energy = energy[16:243]
    energy.drop(energy.columns[0:2],axis=1,inplace=True)
    energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy['Energy Supply']=energy['Energy Supply']*1000000
    energy = energy.replace("...",np.NaN)
    country = []
    for i in energy['Country']:
        pattern = re.compile(r'\D+')
        Country1 = pattern.findall(i)
        newdata =''.join(Country1)
        loc = newdata.find('(')
        if loc >0:
            newdata = newdata[0:loc-1]
        else:
            newdata = newdata
        country.append(newdata.strip())
    energy['Country']=country
    energy.set_index(['Country'],inplace=True)
    country_name = {"Republic of Korea": "South Korea","United States of America": "United States",
     "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"}
    energy.rename(index = country_name,inplace = True)    
    
    GDP = pd.read_csv(r'world_bank.csv',sep=',',skiprows = 4)
    country_name2 ={"Korea, Rep.": "South Korea","Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"}
    GDP['Country Name']=GDP['Country Name'].replace(country_name2)
    
    ScimEn = pd.read_excel(r'scimagojr-3.xlsx')
    
    df1 = pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer'),GDP,left_on='Country',right_on='Country Name',how ='outer')
    df = df1[['Country','Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
        'Citations per document', 'H index', 'Energy Supply',
        'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
        '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
    df.set_index(['Country'],inplace =True)
    df = df.loc[df['Rank'].isin([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])]
    df.sort_index(by = 'Rank', ascending = True,inplace = True)
    return(df)
# print(answer_one())



### Question 2 (6.6%)
# The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

# *This function should return a single number.*
def answer_two():
    energy = pd.read_excel(r'Energy Indicators.xls')
    energy = energy[16:243]
    energy.drop(energy.columns[0:2],axis=1,inplace=True)
    energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy['Energy Supply']=energy['Energy Supply']*1000000
    energy = energy.replace("...",np.NaN)
    country = []
    for i in energy['Country']:
        pattern = re.compile(r'\D+')
        Country1 = pattern.findall(i)
        newdata =''.join(Country1)
        loc = newdata.find('(')
        if loc >0:
            newdata = newdata[0:loc-1]
        else:
            newdata = newdata
        country.append(newdata.strip())
    energy['Country']=country
    energy.set_index(['Country'],inplace=True)
    country_name = {"Republic of Korea": "South Korea","United States of America": "United States",
     "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"}
    energy.rename(index = country_name,inplace = True)    
    
    GDP = pd.read_csv(r'world_bank.csv',sep=',',skiprows = 4)
    country_name2 ={"Korea, Rep.": "South Korea","Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"}
    GDP['Country Name']=GDP['Country Name'].replace(country_name2)
    
    ScimEn = pd.read_excel(r'scimagojr-3.xlsx')
    union =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer'),GDP,left_on='Country',right_index=True,how ='outer')
    intersect =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='inner'),GDP,left_on='Country',right_index=True,how ='inner')
    return len(union)-len(intersect)
print(answer_two())

508

In [12]:
energy = pd.read_excel(r'Energy Indicators.xls')
energy = energy[16:243]
energy.drop(energy.columns[0:2],axis=1,inplace=True)
energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy['Energy Supply']=energy['Energy Supply']*1000000
energy = energy.replace("...",np.NaN)
country = []
for i in energy['Country']:
    pattern = re.compile(r'\D+')
    Country1 = pattern.findall(i)
    newdata =''.join(Country1)
    loc = newdata.find('(')
    if loc >0:
        newdata = newdata[0:loc-1]
    else:
        newdata = newdata
    country.append(newdata.strip())
energy['Country']=country
energy.set_index(['Country'],inplace=True)
country_name = {"Republic of Korea": "South Korea","United States of America": "United States",
 "United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"}
energy.rename(index = country_name,inplace = True)    

GDP = pd.read_csv(r'world_bank.csv',sep=',',skiprows = 4)
country_name2 ={"Korea, Rep.": "South Korea","Iran, Islamic Rep.": "Iran", "Hong Kong SAR, China": "Hong Kong"}
GDP['Country Name']=GDP['Country Name'].replace(country_name2)

ScimEn = pd.read_excel(r'scimagojr-3.xlsx')

#     ScimEn = pd.read_excel(r'scimagojr-3.xlsx')
union =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer'),GDP,left_on='Country',right_index=True,how ='outer')
intersect =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='inner'),GDP,left_on='Country',right_index=True,how ='inner')
len(union)-len(intersect)

508

In [7]:
ScimEn.head()

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,127050,126767,597237,411683,4.70,138
1,2,United States,96661,94747,792274,265436,8.20,230
2,3,Japan,30504,30287,223024,61554,7.31,134
3,4,United Kingdom,20944,20357,206091,37874,9.84,139
4,5,Russian Federation,18534,18301,34266,12422,1.85,57

In [8]:
energy.head()

,Energy Supply,Energy Supply per Capita,% Renewable
Country,,,
Afghanistan,321000000,10.0,78.669280
Albania,102000000,35.0,100.000000
Algeria,1959000000,51.0,0.551010
American Samoa,.................................................,NaN,0.641026
Andorra,9000000,121.0,88.695650

In [9]:
GDP.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
1,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
2,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
3,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
4,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10

In [10]:
pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer')

,Rank,Country,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable
0,1.0,China,127050.0,126767.0,597237.0,411683.0,4.70,138.0,127191000000,93.0,19.754910
1,2.0,United States,96661.0,94747.0,792274.0,265436.0,8.20,230.0,90838000000,286.0,11.570980
2,3.0,Japan,30504.0,30287.0,223024.0,61554.0,7.31,134.0,18984000000,149.0,10.232820
3,4.0,United Kingdom,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7920000000,124.0,10.600470
4,5.0,Russian Federation,18534.0,18301.0,34266.0,12422.0,1.85,57.0,30709000000,214.0,17.288680
5,6.0,Canada,17899.0,17620.0,215003.0,40930.0,12.01,149.0,10431000000,296.0,61.945430
6,7.0,Germany,17027.0,16831.0,140566.0,27426.0,8.26,126.0,13261000000,165.0,17.901530
7,8.0,India,15005.0,14841.0,128763.0,37209.0,8.58,115.0,33195000000,26.0,14.969080
8,9.0,France,13153.0,12973.0,130632.0,28601.0,9.93,114.0,10597000000,166.0,17.020280
9,10.0,South Korea,11983.0,11923.0,114675.0,22595.0,9.57,104.0,11007000000,221.0,2.279353
10,11.0,Italy,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6530000000,109.0,33.667230
11,12.0,Spain,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4923000000,106.0,37.968590
12,13.0,Iran,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9172000000,119.0,5.707721
13,14.0,Australia,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5386000000,231.0,11.810810
14,15.0,Brazil,8668.0,8596.0,60702.0,14396.0,7.00,86.0,12149000000,59.0,69.648030
15,16.0,Taiwan,6468.0,6441.0,86099.0,14768.0,13.31,102.0,NaN,NaN,NaN
16,17.0,Turkey,5879.0,5827.0,91857.0,23165.0,15.62,104.0,4897000000,64.0,28.536690
17,18.0,Norway,5675.0,5634.0,32693.0,6024.0,5.76,74.0,1388000000,273.0,97.635580
18,19.0,Netherlands,5170.0,5105.0,48351.0,6067.0,9.35,85.0,3199000000,190.0,6.324659
19,20.0,Sweden,4565.0,4494.0,57889.0,9632.0,12.68,95.0,2044000000,212.0,46.598460
20,21.0,Malaysia,3914.0,3881.0,25545.0,6597.0,6.53,62.0,3417000000,116.0,7.754589
21,22.0,Switzerland,3636.0,3599.0,38962.0,6186.0,10.72,81.0,1113000000,136.0,57.745480
22,23.0,Denmark,3531.0,3494.0,37254.0,6191.0,10.55,85.0,725000000,129.0,33.537660
23,24.0,Mexico,3249.0,3214.0,21524.0,4145.0,6.62,57.0,7944000000,64.0,12.913400
24,25.0,Poland,3123.0,3102.0,24852.0,5395.0,7.96,55.0,4121000000,107.0,5.537899
25,26.0,Saudi Arabia,2979.0,2930.0,21208.0,2469.0,7.12,61.0,7985000000,264.0,0.000352
26,27.0,Greece,2866.0,2835.0,41662.0,6226.0,14.54,82.0,993000000,90.0,24.795280
27,28.0,Egypt,2789.0,2752.0,19123.0,2778.0,6.86,55.0,3422000000,39.0,8.805713
28,29.0,Belgium,2697.0,2642.0,23720.0,3300.0,8.79,63.0,2338000000,210.0,9.959739
29,30.0,Singapore,2488.0,2443.0,36098.0,3700.0,14.51,81.0,1120000000,207.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
190,NaN,Isle of Man,NaN,NaN,NaN,NaN,NaN,NaN,0,4.0,0.793651
190,NaN,Jersey,NaN,NaN,NaN,NaN,NaN,NaN,3000000,34.0,0.000000
190,NaN,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,1000000,8.0,0.000000
190,NaN,Lao People's Democratic Republic,NaN,NaN,NaN,NaN,NaN,NaN,85000000,13.0,93.290090
190,NaN,Marshall Islands,NaN,NaN,NaN,NaN,NaN,NaN,1000000,28.0,0.000000
190,NaN,Martinique,NaN,NaN,NaN,NaN,NaN,NaN,33000000,84.0,2.607710
190,NaN,Micronesia,NaN,NaN,NaN,NaN,NaN,NaN,2000000,21.0,2.941176
190,NaN,Montserrat,NaN,NaN,NaN,NaN,NaN,NaN,1000000,153.0,0.000000
190,NaN,Niue,NaN,NaN,NaN,NaN,NaN,NaN,0,65.0,0.000000
190,NaN,Northern Mariana Islands,NaN,NaN,NaN,NaN,NaN,NaN,.................................................,NaN,0.000000
190,NaN,Republic of Moldova,NaN,NaN,NaN,NaN,NaN,NaN,93000000,23.0,5.082873
190,NaN,Réunion,NaN,NaN,NaN,NaN,NaN,NaN,59000000,70.0,28.297190
190,NaN,Saint Kitts and Nevis,NaN,NaN,NaN,NaN,NaN,NaN,4000000,73.0,0.000000
190,NaN,Saint Pierre and Miquelon,NaN,NaN,NaN,NaN,NaN,NaN,1000000,162.0,2.127660
190,NaN,Saint Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,NaN,3000000,28.0,16.666670
190,NaN,Sao Tome and Principe,NaN,NaN,NaN,NaN,NaN,NaN,3000000,14.0,10.447760
190,NaN,Sint Maarten,NaN,NaN,NaN,NaN,NaN,NaN,12000000,327.0,0.000000
190,NaN,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,6000000,11.0,0.000000
190,NaN,Somalia,NaN,NaN,NaN,NaN,NaN,NaN,126000000,12.0,0.000000
190,NaN,South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,28000000,2.0,0.423729
190,NaN,State of Palestine,NaN,NaN,NaN,NaN,NaN,NaN,61000000,14.0,0.000000
190,NaN,The former Yugoslav Republic of Macedonia,NaN,NaN,NaN,NaN,NaN,NaN,117000000,56.0,26.140470
190,NaN,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,7000000,6.0,0.000000
190,NaN,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,3000000,28.0,0.000000
190,NaN,Turks and Caicos Islands,NaN,NaN,NaN,NaN,NaN,NaN,3000000,85.0,0.000000
190,NaN,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,.................................................,NaN,0.000000
190,NaN,United Republic of Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,994000000,20.0,31.072840
190,NaN,United States Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,.................................................,NaN,0.000000
190,NaN,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,3000000,10.0,14.705880
190,NaN,Wallis and Futuna Islands,NaN,NaN,NaN,NaN,NaN,NaN,0,26.0,0.000000

In [24]:
import numpy as np
import pandas as pd
import re

# Working till replacing "..." with NaN


energy=pd.read_excel('Energy Indicators.xls',skiprows=17,skipfooter=38)
del energy['Unnamed: 0']
del energy['Unnamed: 1']
energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy['Energy Supply']=1000000*energy['Energy Supply']        #converting peta joules to Gigi joules (1P=1,000,000GJ)
energy['Energy Supply']=pd.to_numeric(energy['Energy Supply'],errors='coerce')

energy = energy.replace("...",np.NaN)
energy = energy.replace('........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................',np.NaN)
# Regex for corecting names with bracket
country_list= []          # list  for storring corrected names of countries
for i in energy['Country']:
    pattern = re.compile(r'\D+')
    Country1 = pattern.findall(i)
    newdata =''.join(Country1)
    loc = newdata.find('(')
    if loc >0:
        newdata = newdata[0:loc-1]
    else:
        newdata = newdata
    country_list.append(newdata.strip())



energy['Country']=country_list        # Replacing old column (Country) with correct name of countries in our list_country

energy.set_index('Country',inplace=True) 

country_name = {"Republic of Korea": "South Korea","United States of America": "United States","United Kingdom of Great Britain and Northern Ireland": "United Kingdom", "China, Hong Kong Special Administrative Region": "Hong Kong"}
energy.rename(index = country_name,inplace = True)


# 3)loading the GDP data from the world bank csv file

GDP=pd.read_csv('world_bank.csv', skiprows=4,skipfooter=0)
GDP.set_index('Country Name',inplace=True)

country2={"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"}

GDP.rename(index = country2,inplace = True) 
#     print(len(GDP.columns))
GDP



# 4a) load the Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology from the file scimagojr-3.xlsx, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame ScimEn.

ScimEn=pd.read_excel("scimagojr-3.xlsx",skiprows=0,skipfooter=0)
ScimEn

# 4b) only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).

ScimEn2=ScimEn[0:15]
#     print(len(ScimEn2.columns))
ScimEn2

# 5) 

# Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). 
#     Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).

# The index of this DataFrame should be the name of the country, and the columns should be 
# ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index',
#  'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', 
#  '2012', '2013', '2014', '2015'].

df_GDP_ScimEn=pd.merge(ScimEn2, GDP,how ='inner', on=None, left_on='Country', left_index=False, right_index=True, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)
#     print(len(df_GDP_ScimEn.columns))
df_GDP_ScimEn

#6

df_GDP_ScimEn_Energy=pd.merge(df_GDP_ScimEn,energy,how ='inner',left_on='Country',   left_index=False, right_index=True, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)
#     print(len(df_GDP_ScimEn_Energy.columns))
# df_GDP_ScimEn_Energy=pd.merge(energy,df_GDP_ScimEn,how ='right', on='Country',  left_index=False, right_index=True, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False)
df_GDP_ScimEn_Energy

df=df_GDP_ScimEn_Energy[['Country','Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
#     print(len(df.columns))
df.set_index('Country',inplace=True)
df

###############
# union =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='outer'),GDP,left_on='Country',right_index=True,how ='outer')
# intersect =  pd.merge(pd.merge(ScimEn,energy,left_on='Country',right_index=True,how ='inner'),GDP,left_on='Country',right_index=True,how ='inner')
# (len(union)-len(intersect))

####################

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,1.271910e+11,93.0,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,9.083800e+10,286.0,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,1.898400e+10,149.0,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7.920000e+09,124.0,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,3.070900e+10,214.0,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,1.043100e+10,296.0,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,1.326100e+10,165.0,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,3.319500e+10,26.0,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,1.059700e+10,166.0,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,1.100700e+10,221.0,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6.530000e+09,109.0,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4.923000e+09,106.0,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9.172000e+09,119.0,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5.386000e+09,231.0,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,1.214900e+10,59.0,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [44]:
#3
avgGDP=df[['2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1)
k=avgGDP.sort_values()
k

Country
Iran                  4.441558e+11
South Korea           1.106715e+12
Australia             1.164043e+12
Spain                 1.418078e+12
Russian Federation    1.565459e+12
Canada                1.660647e+12
India                 1.769297e+12
Italy                 2.120175e+12
Brazil                2.189794e+12
United Kingdom        2.487907e+12
France                2.681725e+12
Germany               3.493025e+12
Japan                 5.542208e+12
China                 6.348609e+12
United States         1.536434e+13
dtype: float64

In [42]:
type(avgGDP)

pandas.core.series.Series

In [49]:
# Question 4 (6.6%)
# By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

# This function should return a single number.


k.index

Index(['Iran', 'South Korea', 'Australia', 'Spain', 'Russian Federation',
       'Canada', 'India', 'Italy', 'Brazil', 'United Kingdom', 'France',
       'Germany', 'Japan', 'China', 'United States'],
      dtype='object', name='Country')

In [52]:
k.iloc[5]

1660647466307.512

In [53]:
Top15 = answer_one()
avgGDP=Top15[['2006', '2007', '2008',
   '2009', '2010', '2011', '2012', '2013', '2014', '2015']].mean(axis=1)
k=avgGDP.sort_values()
#     GDP_change = k.ix[5]['2015']-k.ix[5]['2006']
Top15['avgGDP']=k
Top15.sort_values(by='avgGDP',inplace=True,ascending = False)
GDP_change =Top15.iloc[5]['2015']-Top15.iloc[5]['2006']
GDP_change

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

246702696075.3999

In [ ]:
# Question 6 (6.6%)
# What country has the maximum % Renewable and what is the percentage?

# This function should return a tuple with the name of the country and the percentage.

In [65]:

Top15 = answer_one()

Top15.sort_values(by='% Renewable',inplace=True,ascending = False)
Top15.index[0]
# Top15
k=Top15.index[0],Top15.iloc[0]['% Renewable']
list(k)

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

['Brazil', 69.64803]

In [93]:
# Question 7 (6.6%)
# Create a new column that is the ratio of Self-Citations to Total Citations. What is the maximum value for this new column, and what country has the highest ratio?

# This function should return a tuple with the name of the country and the ratio.

Top15 = answer_one()
Top15['ratio_Self-Citations_TotalCitations']=Top15['Self-citations']/(Top15['Self-citations'].sum())
Top15['ratio_Self-Citations_TotalCitations'].max()
# total = Top15['Self-citations'].sum(axis=0,skipna=False)
# total
Top15

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,ratio_Self-Citations_TotalCitations
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,127191000000,93.0,19.754910,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.393773
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,90838000000,286.0,11.570980,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.253889
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,18984000000,149.0,10.232820,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.058876
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7920000000,124.0,10.600470,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.036226
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,30709000000,214.0,17.288680,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.011882
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,10431000000,296.0,61.945430,...,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.039149
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,13261000000,165.0,17.901530,...,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.026233
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,33195000000,26.0,14.969080,...,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.035590
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,10597000000,166.0,17.020280,...,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.027357
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,11007000000,221.0,2.279353,...,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.021612
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6530000000,109.0,33.667230,...,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.025501
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4923000000,106.0,37.968590,...,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.022921
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9172000000,119.0,5.707721,...,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.018293
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5386000000,231.0,11.810810,...,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.014927
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,12149000000,59.0,69.648030,...,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.013770

In [110]:
def answer_seven():
    df = answer_one()
    total = df['Self-citations'].sum(axis=0,skipna=False)
    df['Citations_ratio']=df['Self-citations']/total
    df.sort_values(by='Self-citations',ascending = False,inplace = True)
    return(df.iloc[0].name,df['Citations_ratio'][0])
print(answer_seven())

('China', 0.3937733982985838)

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

In [128]:
# def answer_seven():
#     df = answer_one()
#     total = df['Self-citations'].sum(axis=0,skipna=False)
#     df['Citations_ratio']=df['Self-citations']/total
#     df.sort_values(by='Self-citations',ascending = False,inplace = True)
#     return(df.iloc[0].name,df['Citations_ratio'][0])
# print(answer_seven())

def answer_seven():
    Top15 = answer_one()
    Top15 = answer_one()
    Top15['Citations_ratio']=Top15['Self-citations']/Top15['Citations']
    Top15['Citations_ratio'].max()
    Top15.sort_values(by='Citations_ratio',inplace=True,ascending=False)
    return (Top15.iloc[0].name,Top15['Citations_ratio'][0])
answer_seven()

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

('China', 0.6893126179389422)

In [127]:
def ratio(row):
    row['ratio'] = row['Self-citations'] / row['Citations']
    return row

def answer_seven():
    Top15 = answer_one()
    new = Top15.apply(ratio, axis=1)
    m = float(np.max(new['ratio']))
    country = new[new['ratio'] == m].iloc[0].name
    return country, m
answer_seven()

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

('China', 0.6893126179389422)

In [86]:
Top15

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,ratio_Self-Citations_TotalCitations
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,127191000000,93.0,19.754910,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,0.136019
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,90838000000,286.0,11.570980,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0.087699
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,18984000000,149.0,10.232820,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0.020337
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7920000000,124.0,10.600470,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0.012513
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,30709000000,214.0,17.288680,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,0.004104
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,10431000000,296.0,61.945430,...,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,0.013523
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,13261000000,165.0,17.901530,...,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,0.009061
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,33195000000,26.0,14.969080,...,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0.012294
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,10597000000,166.0,17.020280,...,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,0.009450
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,11007000000,221.0,2.279353,...,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0.007465
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6530000000,109.0,33.667230,...,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,0.008809
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4923000000,106.0,37.968590,...,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,0.007918
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9172000000,119.0,5.707721,...,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0.006319
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5386000000,231.0,11.810810,...,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0.005156
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,12149000000,59.0,69.648030,...,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,0.004756

In [83]:
# Question 8 (6.6%)
# Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
# What is the third most populous country according to this estimate?

# This function should return a single string value.

# def answer_eight():
Top15 = answer_one()
# return "ANSWER"

Top15['population']=Top15['Energy Supply']/Top15['Energy Supply per Capita']
Top15.sort_values(by='population',inplace=True,ascending=False)
Top15.index[2]

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

'United States'

In [109]:
# Question 9 (6.6%)
# Create a column that estimates the number of citable documents per person. What is the correlation between 
# the number of citable documents per capita and the energy supply per capita? 
# Use the .corr() method, (Pearson's correlation).

# This function should return a single number.

# (Optional: Use the built-in function plot9() to visualize the relationship between Energy Supply per Capita vs. 
# Citable docs per Capita)

# df['population']=df['Energy Supply']/df['Energy Supply per Capita']
# df['citable documents per person']=df['Citable documents']/df['population']
# df['citable documents per person']=np.float64(df['citable documents per person'])

Top15= answer_one()
Top15['population']=Top15['Energy Supply']/Top15['Energy Supply per Capita']
Top15['citable_per_person']=Top15['Citable documents']/Top15['population']
Top15['citable_per_person']=np.float64(Top15['Citable documents']/Top15['population'])
relation =Top15['citable_per_person'].corr(Top15['Energy Supply per Capita'])


relation

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

0.7940010435442942

In [103]:
Top15

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2008,2009,2010,2011,2012,2013,2014,2015,population,citable_per_person
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,127191000000,93.0,19.754910,...,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.36765e+09,9.269e-05
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,90838000000,286.0,11.570980,...,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,3.17615e+08,0.000298307
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,18984000000,149.0,10.232820,...,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1.27409e+08,0.000237714
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7920000000,124.0,10.600470,...,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,6.3871e+07,0.000318721
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,30709000000,214.0,17.288680,...,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1.435e+08,0.000127533
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,10431000000,296.0,61.945430,...,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,3.52399e+07,0.000500002
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,13261000000,165.0,17.901530,...,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,8.03697e+07,0.00020942
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,33195000000,26.0,14.969080,...,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,1.27673e+09,1.16242e-05
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,10597000000,166.0,17.020280,...,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,6.38373e+07,0.00020322
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,11007000000,221.0,2.279353,...,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,4.98054e+07,0.000239392
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6530000000,109.0,33.667230,...,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,5.99083e+07,0.000180175
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4923000000,106.0,37.968590,...,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,4.64434e+07,0.00020089
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9172000000,119.0,5.707721,...,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,7.70756e+07,0.00011442
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5386000000,231.0,11.810810,...,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,2.3316e+07,0.000374206
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,12149000000,59.0,69.648030,...,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,2.05915e+08,4.17453e-05

In [105]:
def answer_nine():
    df = answer_one()
    df['population']=df['Energy Supply']/df['Energy Supply per Capita']
    df['citable documents per person']=df['Citable documents']/df['population']
    df['citable documents per person']=np.float64(df['citable documents per person'])
    relation = df['citable documents per person'].corr(df['Energy Supply per Capita'])
    return(relation)
print(answer_nine())

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

0.7940010435442942

In [126]:

# Question 10 (6.6%)
# Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15,
# and a 0 if the country's % Renewable value is below the median.

# This function should return a series named HighRenew whose index is the country name sorted in ascending order of rank.
df = answer_one()
M=df['% Renewable'].median()

df['Flag']=df['% Renewable'].map(lambda x:1 if x>=M else 0)

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

In [115]:
def func(x,M):
    if x>=M:
        return 1
    elif x<M:
        return 0

In [123]:
df

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,HighRenew
Country,,,,,,,,,,,,,,,,,,,,,
China,1.0,127050.0,126767.0,597237.0,411683.0,4.70,138.0,127191000000,93.0,19.754910,...,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1
United States,2.0,96661.0,94747.0,792274.0,265436.0,8.20,230.0,90838000000,286.0,11.570980,...,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,0
Japan,3.0,30504.0,30287.0,223024.0,61554.0,7.31,134.0,18984000000,149.0,10.232820,...,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,0
United Kingdom,4.0,20944.0,20357.0,206091.0,37874.0,9.84,139.0,7920000000,124.0,10.600470,...,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,0
Russian Federation,5.0,18534.0,18301.0,34266.0,12422.0,1.85,57.0,30709000000,214.0,17.288680,...,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,1
Canada,6.0,17899.0,17620.0,215003.0,40930.0,12.01,149.0,10431000000,296.0,61.945430,...,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,1
Germany,7.0,17027.0,16831.0,140566.0,27426.0,8.26,126.0,13261000000,165.0,17.901530,...,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,1
India,8.0,15005.0,14841.0,128763.0,37209.0,8.58,115.0,33195000000,26.0,14.969080,...,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,0
France,9.0,13153.0,12973.0,130632.0,28601.0,9.93,114.0,10597000000,166.0,17.020280,...,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,1
South Korea,10.0,11983.0,11923.0,114675.0,22595.0,9.57,104.0,11007000000,221.0,2.279353,...,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,0
Italy,11.0,10964.0,10794.0,111850.0,26661.0,10.20,106.0,6530000000,109.0,33.667230,...,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,1
Spain,12.0,9428.0,9330.0,123336.0,23964.0,13.08,115.0,4923000000,106.0,37.968590,...,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,1
Iran,13.0,8896.0,8819.0,57470.0,19125.0,6.46,72.0,9172000000,119.0,5.707721,...,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,0
Australia,14.0,8831.0,8725.0,90765.0,15606.0,10.28,107.0,5386000000,231.0,11.810810,...,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,0
Brazil,15.0,8668.0,8596.0,60702.0,14396.0,7.00,86.0,12149000000,59.0,69.648030,...,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,1

In [129]:
def func(row):
    if x>=M:
        return 1
    elif x<M:
        return 0

def answer_seven():
    Top15 = answer_one()
    flag= Top15.apply(func, axis=1)
    m = float(np.max(flag['ratio']))
    country = flag[flag['ratio'] == m].iloc[0].name
    return country, m
answer_seven()

# df = answer_one()
# M=df['% Renewable'].median()

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

NameError: ("name 'x' is not defined", 'occurred at index China')

In [130]:
# Question 11 (6.6%)
# Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size
# (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of 
# each country.

# ContinentDict  = {'China':'Asia', 
#                   'United States':'North America', 
#                   'Japan':'Asia', 
#                   'United Kingdom':'Europe', 
#                   'Russian Federation':'Europe', 
#                   'Canada':'North America', 
#                   'Germany':'Europe', 
#                   'India':'Asia',
#                   'France':'Europe', 
#                   'South Korea':'Asia', 
#                   'Italy':'Europe', 
#                   'Spain':'Europe', 
#                   'Iran':'Asia',
#                   'Australia':'Australia', 
#                   'Brazil':'South America'}
# This function should return a DataFrame with index named Continent ['Asia', 'Australia', 'Europe', 'North America', 'South America'] and columns ['size', 'sum', 'mean', 'std']

In [178]:
df = answer_one()
df['population']=df['Energy Supply']/df['Energy Supply per Capita']
df['population'] = np.float64(df['population'])
df['country']=df.index
ContinentDict = {'China':'Asia', 'United States':'North America', 'Japan':'Asia', 'United Kingdom':'Europe', 'Russian Federation':'Europe', 'Canada':'North America',
 'Germany':'Europe',
 'India':'Asia',
 'France':'Europe',
 'South Korea':'Asia',
 'Italy':'Europe',
 'Spain':'Europe',
 'Iran':'Asia',
 'Australia':'Australia',
 'Brazil':'South America'}

df.rename(index=ContinentDict,inplace=True)

df['Continent']=df.index
df.reset_index(inplace = True)
result= df.groupby('Continent')['population'].agg(['size', 'sum','mean','std'])
# result = df[['Country','population']].groupby('Country').agg(['size', 'sum', 'mean', 'std'])
result
# df

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN

In [159]:
ContinentDict  = {'China':'Asia',
                  'United States':'North America',
                  'Japan':'Asia',
                  'United Kingdom':'Europe',
                  'Russian Federation':'Europe',
                  'Canada':'North America',
                  'Germany':'Europe',
                  'India':'Asia',
                  'France':'Europe',
                  'South Korea':'Asia',
                  'Italy':'Europe',
                  'Spain':'Europe',
                  'Iran':'Asia',
                  'Australia':'Australia',
                  'Brazil':'South America'}

def answer_eleven():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    for i in range(len(Top15)):
        country = Top15.iloc[i].name
        Top15.set_value(country, 'Continent', ContinentDict[country])
    Top15 = (Top15.reset_index(level=0).set_index(['Continent', 'Country']))
#     Top15 = Top15.groupby(['Continent','Country'])['PopEst'].agg(['size', 'sum', 'mean', 'std'])
    return Top15
answer_eleven()

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

                                  Rank  Documents  Citable documents  \
Continent     Country
Asia          China                1.0   127050.0           126767.0
North America United States        2.0    96661.0            94747.0
Asia          Japan                3.0    30504.0            30287.0
Europe        United Kingdom       4.0    20944.0            20357.0
              Russian Federation   5.0    18534.0            18301.0
North America Canada               6.0    17899.0            17620.0
Europe        Germany              7.0    17027.0            16831.0
Asia          India                8.0    15005.0            14841.0
Europe        France               9.0    13153.0            12973.0
Asia          South Korea         10.0    11983.0            11923.0
Europe        Italy               11.0    10964.0            10794.0
              Spain               12.0     9428.0             9330.0
Asia          Iran                13.0     8896.0             8819.0
Australia     Australia           14.0     8831.0             8725.0
South America Brazil              15.0     8668.0             8596.0

                                  Citations  Self-citations  \
Continent     Country
Asia          China                597237.0        411683.0
North America United States        792274.0        265436.0
Asia          Japan                223024.0         61554.0
Europe        United Kingdom       206091.0         37874.0
              Russian Federation    34266.0         12422.0
North America Canada               215003.0         40930.0
Europe        Germany              140566.0         27426.0
Asia          India                128763.0         37209.0
Europe        France               130632.0         28601.0
Asia          South Korea          114675.0         22595.0
Europe        Italy                111850.0         26661.0
              Spain                123336.0         23964.0
Asia          Iran                  57470.0         19125.0
Australia     Australia             90765.0         15606.0
South America Brazil                60702.0         14396.0

                                  Citations per document  H index  \
Continent     Country
Asia          China                                 4.70    138.0
North America United States                         8.20    230.0
Asia          Japan                                 7.31    134.0
Europe        United Kingdom                        9.84    139.0
              Russian Federation                    1.85     57.0
North America Canada                               12.01    149.0
Europe        Germany                               8.26    126.0
Asia          India                                 8.58    115.0
Europe        France                                9.93    114.0
Asia          South Korea                           9.57    104.0
Europe        Italy                                10.20    106.0
              Spain                                13.08    115.0
Asia          Iran                                  6.46     72.0
Australia     Australia                            10.28    107.0
South America Brazil                                7.00     86.0

                                 Energy Supply  Energy Supply per Capita  \
Continent     Country
Asia          China               127191000000                      93.0
North America United States        90838000000                     286.0
Asia          Japan                18984000000                     149.0
Europe        United Kingdom        7920000000                     124.0
              Russian Federation   30709000000                     214.0
North America Canada               10431000000                     296.0
Europe        Germany              13261000000                     165.0
Asia          India                33195000000                      26.0
Europe        France               10597000000                     166.0
Asia          South Korea          11007000000                     221.0
Europe        Italy                 6530000000                     109.0
              Spain                 4923000000                     106.0
Asia          Iran                  9172000000                     119.0
Australia     Australia             5386000000                     231.0
South America Brazil               12149000000                      59.0

                                  % Renewable     ...               2007  \
Continent     Country                             ...
Asia          China                 19.754910     ...       4.559041e+12
North America United States         11.570980     ...       1.505540e+13
Asia          Japan                 10.232820     ...       5.617036e+12
Europe        United Kingdom        10.600470     ...       2.482203e+12
              Russian Federation    17.288680     ...       1.504071e+12
North America Canada                61.945430     ...       1.596740e+12
Europe        Germany               17.901530     ...       3.441561e+12
Asia          India                 14.969080     ...       1.374865e+12
Europe        France                17.020280     ...       2.669424e+12
Asia          South Korea            2.279353     ...       9.924316e+11
Europe        Italy                 33.667230     ...       2.234627e+12
              Spain                 37.968590     ...       1.468146e+12
Asia          Iran                   5.707721     ...       4.250646e+11
Australia     Australia             11.810810     ...       1.060340e+12
South America Brazil                69.648030     ...       1.957118e+12

                                          2008          2009          2010  \
Continent     Country
Asia          China               4.997775e+12  5.459247e+12  6.039659e+12
North America United States       1.501149e+13  1.459484e+13  1.496437e+13
Asia          Japan               5.558527e+12  5.251308e+12  5.498718e+12
Europe        United Kingdom      2.470614e+12  2.367048e+12  2.403504e+12
              Russian Federation  1.583004e+12  1.459199e+12  1.524917e+12
North America Canada              1.612713e+12  1.565145e+12  1.613406e+12
Europe        Germany             3.478809e+12  3.283340e+12  3.417298e+12
Asia          India               1.428361e+12  1.549483e+12  1.708459e+12
Europe        France              2.674637e+12  2.595967e+12  2.646995e+12
Asia          South Korea         1.020510e+12  1.027730e+12  1.094499e+12
Europe        Italy               2.211154e+12  2.089938e+12  2.125185e+12
              Spain               1.484530e+12  1.431475e+12  1.431673e+12
Asia          Iran                4.289909e+11  4.389208e+11  4.677902e+11
Australia     Australia           1.099644e+12  1.119654e+12  1.142251e+12
South America Brazil              2.056809e+12  2.054215e+12  2.208872e+12

                                          2011          2012          2013  \
Continent     Country
Asia          China               6.612490e+12  7.124978e+12  7.672448e+12
North America United States       1.520402e+13  1.554216e+13  1.577367e+13
Asia          Japan               5.473738e+12  5.569102e+12  5.644659e+12
Europe        United Kingdom      2.450911e+12  2.479809e+12  2.533370e+12
              Russian Federation  1.589943e+12  1.645876e+12  1.666934e+12
North America Canada              1.664087e+12  1.693133e+12  1.730688e+12
Europe        Germany             3.542371e+12  3.556724e+12  3.567317e+12
Asia          India               1.821872e+12  1.924235e+12  2.051982e+12
Europe        France              2.702032e+12  2.706968e+12  2.722567e+12
Asia          South Korea         1.134796e+12  1.160809e+12  1.194429e+12
Europe        Italy               2.137439e+12  2.077184e+12  2.040871e+12
              Spain               1.417355e+12  1.380216e+12  1.357139e+12
Asia          Iran                4.853309e+11  4.532569e+11  4.445926e+11
Australia     Australia           1.169431e+12  1.211913e+12  1.241484e+12
South America Brazil              2.295245e+12  2.339209e+12  2.409740e+12

                                          2014          2015       PopEst
Continent     Country
Asia          China               8.230121e+12  8.797999e+12  1.36765e+09
North America United States       1.615662e+13  1.654857e+13  3.17615e+08
Asia          Japan               5.642884e+12  5.669563e+12  1.27409e+08
Europe        United Kingdom      2.605643e+12  2.666333e+12   6.3871e+07
              Russian Federation  1.678709e+12  1.616149e+12    1.435e+08
North America Canada              1.773486e+12  1.792609e+12  3.52399e+07
Europe        Germany             3.624386e+12  3.685556e+12  8.03697e+07
Asia          India               2.200617e+12  2.367206e+12  1.27673e+09
Europe        France              2.729632e+12  2.761185e+12  6.38373e+07
Asia          South Korea         1.234340e+12  1.266580e+12  4.98054e+07
Europe        Italy               2.033868e+12  2.049316e+12  5.99083e+07
              Spain               1.375605e+12  1.419821e+12  4.64434e+07
Asia          Iran                4.639027e+11           NaN  7.70756e+07
Australia     Australia           1.272520e+12  1.301251e+12   2.3316e+07
South America Brazil              2.412231e+12  2.319423e+12  2.05915e+08

[15 rows x 21 columns]

In [141]:
# Question 12 (6.6%)
# Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins.
# How many countries are in each of these groups?

# This function should return a Series with a MultiIndex of Continent, then the bins for % Renewable.
# Do not include groups with no countries.

In [160]:
def answer_twelve():
    df=answer_one()
    df['bin'] = pd.cut(df['% Renewable'],5)
    df['% Renewable'] = np.float64(df['% Renewable'])
    ContinentDict = {'China':'Asia', 'United States':'North America', 'Japan':'Asia', 'United Kingdom':'Europe', 'Russian Federation':'Europe', 'Canada':'North America',
 'Germany':'Europe',
 'India':'Asia',
 'France':'Europe',
 'South Korea':'Asia',
 'Italy':'Europe',
 'Spain':'Europe',
 'Iran':'Asia',
 'Australia':'Australia',
 'Brazil':'South America'}  
    df.rename(index=ContinentDict,inplace= True) 
    df.reset_index(inplace = True)
    grouped = df.groupby(['Country','bin'])
    
    return(grouped.size())
print(answer_twelve())

Country        bin
Asia           (2.212, 15.753]     4
               (15.753, 29.227]    1
Australia      (2.212, 15.753]     1
Europe         (2.212, 15.753]     1
               (15.753, 29.227]    3
               (29.227, 42.701]    2
North America  (2.212, 15.753]     1
               (56.174, 69.648]    1
South America  (56.174, 69.648]    1
dtype: int64

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

In [161]:
def answer_thirteen():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15 = Top15['PopEst']
    for i in range(len(Top15)):
        country = Top15.keys()[i]
        number = "{:,}".format((Top15.iloc[i]))
        Top15.replace(Top15.iloc[i], number, inplace=True)
    return Top15
answer_thirteen()

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:85: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)

Country
China                 1,367,645,161.2903225
United States          317,615,384.61538464
Japan                  127,409,395.97315437
United Kingdom         63,870,967.741935484
Russian Federation            143,500,000.0
Canada                  35,239,864.86486486
Germany                 80,369,696.96969697
India                 1,276,730,769.2307692
France                  63,837,349.39759036
South Korea            49,805,429.864253394
Italy                  59,908,256.880733944
Spain                    46,443,396.2264151
Iran                    77,075,630.25210084
Australia              23,316,017.316017315
Brazil                 205,915,254.23728815
Name: PopEst, dtype: object