# Merging DataFrame

## Querying 1D series Data Structure and 2D (DataFrame) Data Structure 
### using Loc or iloc for Row querying and square brackets[ ] on object itself for Column based Query
we can query a DataFrame in Series using Boolean masking 
-Boolean masking is a powerful filtering method whic allows us to use broadcasting to determine what data shold be kepth in our analysis

In [1]:
import pandas as pd

purchase_1=pd.Series({'Name':'chris',
                      'item_purschased':'Dog food',
                     'cost':22.50})
purchase_2=pd.Series({'Name':'Keyvn',
                      'item_purschased':'kitty litter',
                     'cost':2.50})
purchase_3=pd.Series({'Name':'Vinod',
                      'item_purschased':'bird seed',
                     'cost':5.0})
df=pd.DataFrame([purchase_1,purchase_2,purchase_3],index=['Store 1','Store 2','Store 3'])
df

          Name  cost item_purschased
Store 1  chris  22.5        Dog food
Store 2  Keyvn   2.5    kitty litter
Store 3  Vinod   5.0       bird seed

## Adding Horizontally by using the column name and default scaler value

In [2]:
df['Delivered']=True
df

          Name  cost item_purschased  Delivered
Store 1  chris  22.5        Dog food       True
Store 2  Keyvn   2.5    kitty litter       True
Store 3  Vinod   5.0       bird seed       True

## Adding Horizontally by using the column name and different values in a Series but the list must be of same length as of dataFrame.

In [3]:
df['Date']=['December 1','January 1','Mid May']

df

          Name  cost item_purschased  Delivered        Date
Store 1  chris  22.5        Dog food       True  December 1
Store 2  Keyvn   2.5    kitty litter       True   January 1
Store 3  Vinod   5.0       bird seed       True     Mid May

In [4]:
df['Sery']=pd.Series({'Name':'Vinod',
                      'item_purschased':'bird seed',
                     'cost':5.0})
df

          Name  cost item_purschased  Delivered        Date Sery
Store 1  chris  22.5        Dog food       True  December 1  NaN
Store 2  Keyvn   2.5    kitty litter       True   January 1  NaN
Store 3  Vinod   5.0       bird seed       True     Mid May  NaN

## Adding  Series with lenght less than length of DatFrame

### 1) we have to Manually enter None or NaN where value is missing 
### 2) We have to pass a Dictionary as Series  such that keys of dictionary  mathching index of DatFrame will  help placing value at desired indices and missing will be left to NaN

In [5]:
adf=df.reset_index()
adf

     index   Name  cost item_purschased  Delivered        Date Sery
0  Store 1  chris  22.5        Dog food       True  December 1  NaN
1  Store 2  Keyvn   2.5    kitty litter       True   January 1  NaN
2  Store 3  Vinod   5.0       bird seed       True     Mid May  NaN

In [6]:
adf['Date']=pd.Series({0:'December 1',2:'Mid May'})
adf

     index   Name  cost item_purschased  Delivered        Date Sery
0  Store 1  chris  22.5        Dog food       True  December 1  NaN
1  Store 2  Keyvn   2.5    kitty litter       True         NaN  NaN
2  Store 3  Vinod   5.0       bird seed       True     Mid May  NaN

## Adding Horizontally by using the column name and a scaller value

In [7]:
df=df.append(pd.Series(data={'Cost':3.00,'Item Purchased':'Kitty Food'},name=('Store 4')))
df

,Name,cost,item_purschased,Delivered,Date,Sery,Cost,Item Purchased
Store 1,chris,22.5,Dog food,1.0,December 1,NaN,NaN,NaN
Store 2,Keyvn,2.5,kitty litter,1.0,January 1,NaN,NaN,NaN
Store 3,Vinod,5.0,bird seed,1.0,Mid May,NaN,NaN,NaN
Store 4,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Kitty Food

##  c) Merging two DataFrame

### 1)  Union = Outer Join
### 2) Intersection= Inner Join

In [8]:
# Creating Two dataframes  with Name Column as its index

staff_df=pd.DataFrame([{'Name':'Kelly','Role':'Director HR'},
                 {'Name':'Sally','Role':'Course Liasion'},
                 {'Name':'James','Role':'Grader'}])
staff_df.set_index('Name')

student_df=pd.DataFrame([{'Name':'James','School':'Director HR'},
                 {'Name':'Mike','School':'Law'},
                 {'Name':'Sally','School':'Engineering'}])
student_df.set_index('Name')

print(staff_df)
print("\n")
print(student_df)

    Name            Role
0  Kelly     Director HR
1  Sally  Course Liasion
2  James          Grader


    Name       School
0  James  Director HR
1   Mike          Law
2  Sally  Engineering

## 1) Merge using Outer joint or Union

In [9]:
pd.merge(staff_df,student_df, how='outer',left_index=True,right_index=True)

  Name_x            Role Name_y       School
0  Kelly     Director HR  James  Director HR
1  Sally  Course Liasion   Mike          Law
2  James          Grader  Sally  Engineering

In [10]:
pd.merge(staff_df,student_df, how='outer')

    Name            Role       School
0  Kelly     Director HR          NaN
1  Sally  Course Liasion  Engineering
2  James          Grader  Director HR
3   Mike             NaN          Law


## 2) Intersection using inner joint

In [11]:
pd.merge(staff_df,student_df, how='inner')

    Name            Role       School
0  Sally  Course Liasion  Engineering
1  James          Grader  Director HR

In [12]:
pd.merge(staff_df,student_df, how='inner',left_index=True,right_index=True)

  Name_x            Role Name_y       School
0  Kelly     Director HR  James  Director HR
1  Sally  Course Liasion   Mike          Law
2  James          Grader  Sally  Engineering

## d) Merge only Staff who may be students also

In [13]:
pd.merge(staff_df,student_df,how='left')

    Name            Role       School
0  Kelly     Director HR          NaN
1  Sally  Course Liasion  Engineering
2  James          Grader  Director HR

### e) Merge only who are student or may be staff also

In [14]:
pd.merge(staff_df,student_df,how='right')

    Name            Role       School
0  Sally  Course Liasion  Engineering
1  James          Grader  Director HR
2   Mike             NaN          Law

## Challenging Exercise

In [32]:
products_df=pd.DataFrame([{'Product ID':'4109','Price':5.0,'Product':'Sushi Roll'},
                          {'Product ID':'1412','Price':0.5,'Product':'Egg'},
                          {'Product ID':'8931','Price':1.5,'Product':'Bagel'}])
products_df.set_index('Product ID')

invoices_df=pd.DataFrame([{'Customer':'Ali','Product ID':'4109','Quantity':1},
                          {'Customer':'Eric','Product ID':'1412','Quantity':12},
                          {'Customer':'Ande','Product ID':'8931','Quantity':6},
                          {'Customer':'Sam','Product ID':'4109','Quantity':2}])
invoices_df.set_index('Product ID')

           Customer  Quantity
Product ID
4109            Ali         1
1412           Eric        12
8931           Ande         6
4109            Sam         2

In [34]:
invoices_df

  Customer Product ID  Quantity
0      Ali       4109         1
1     Eric       1412        12
2     Ande       8931         6
3      Sam       4109         2

In [35]:
products_df

   Price     Product Product ID
0    5.0  Sushi Roll       4109
1    0.5         Egg       1412
2    1.5       Bagel       8931

In [36]:
df0=pd.merge(invoices_df,products_df,how='outer')
df0

  Customer Product ID  Quantity  Price     Product
0      Ali       4109         1    5.0  Sushi Roll
1      Sam       4109         2    5.0  Sushi Roll
2     Eric       1412        12    0.5         Egg
3     Ande       8931         6    1.5       Bagel

In [37]:
df0['Sum Price']=df0['Quantity']*df0['Price']
df0

  Customer Product ID  Quantity  Price     Product  Sum Price
0      Ali       4109         1    5.0  Sushi Roll        5.0
1      Sam       4109         2    5.0  Sushi Roll       10.0
2     Eric       1412        12    0.5         Egg        6.0
3     Ande       8931         6    1.5       Bagel        9.0

In [38]:
df0['Sum Price'].sum()

30.0

In [46]:


# solution
print(pd.merge(products_df, invoices_df, left_index=True, right_on='Product ID'))

Empty DataFrame
Columns: [Product ID, Price, Product, Product ID_x, Customer, Product ID_y, Quantity]
Index: []

In [40]:
pd.merge(products_df, invoices_df, left_index=True, right_on='Product ID')

Empty DataFrame
Columns: [Product ID, Price, Product, Product ID_x, Customer, Product ID_y, Quantity]
Index: []

In [45]:
products_df.set_index('Product ID')
invoices_df.set_index('Product ID')
pd.merge(products_df, invoices_df)
# invoices_df

   Price     Product Product ID Customer  Quantity
0    5.0  Sushi Roll       4109      Ali         1
1    5.0  Sushi Roll       4109      Sam         2
2    0.5         Egg       1412     Eric        12
3    1.5       Bagel       8931     Ande         6

## Multi Index Merge

### First Name of Student and Staff might overlap but last name might not:
### thats why we use list of multiple column as left_on and right_on

In [68]:
staff_df=pd.DataFrame([{'First Name':'Kelly','Last_Name':'Dejardeen','Role':'director HR'},
                       {'First Name':'Sally','Last_Name':'Brooks','Role':'course Liasion'},
                       {'First Name':'James','Last_Name':'Wilde','Role':'Grader'}])

student_df=pd.DataFrame([{'First Name':'James','Last_Name':'Hamound','Role':'Business'},
                       {'First Name':'Mike','Last_Name':'Smith','Role':'Law'},
                       {'First Name':'Sally','Last_Name':'Brooks','Role':'Engineering'}])

In [75]:
student_df

  First Name Last_Name         Role
0      James   Hamound     Business
1       Mike     Smith          Law
2      Sally    Brooks  Engineering

In [76]:
staff_df

  First Name  Last_Name            Role
0      Kelly  Dejardeen     director HR
1      Sally     Brooks  course Liasion
2      James      Wilde          Grader

In [77]:
pd.merge(student_df,staff_df,how='outer')

  First Name  Last_Name            Role
0      James    Hamound        Business
1       Mike      Smith             Law
2      Sally     Brooks     Engineering
3      Kelly  Dejardeen     director HR
4      Sally     Brooks  course Liasion
5      James      Wilde          Grader

In [78]:
pd.merge(student_df,staff_df,how='inner')

Empty DataFrame
Columns: [First Name, Last_Name, Role]
Index: []

## First Name of Student and Staff might overlap but last name might not:

### thats why we use list of multiple column as left_on and right_on

## right_on: Columns from the right DataFrame to use as keys

In [72]:
pd.merge(student_df,staff_df,how='inner',left_on=['First Name','Last_Name'],right_on=['First Name','Last_Name'])

  First Name Last_Name       Role_x          Role_y
0      Sally    Brooks  Engineering  course Liasion

In [83]:
pd.merge(student_df,staff_df,right_on=['First Name'],left_on=['Last_Name'])

Empty DataFrame
Columns: [First Name_x, Last_Name_x, Role_x, First Name_y, Last_Name_y, Role_y]
Index: []

### Since the column are not specified explicitly , merge uses the overlapping column names as the keys.

If the column names are different in each object, you can specify them separately using left_on and Right_on:

In [84]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df3

   data1 lkey
0      0    b
1      1    b
2      2    a
3      3    c
4      4    a
5      5    a
6      6    b

In [85]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})
df4

   data2 rkey
0      0    a
1      1    b
2      2    d

In [96]:
pd.merge(df3, df4,left_on='lkey', right_on='rkey')

   data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [94]:
pd.merge(df3,df4, how='outer')

MergeError: No common columns to perform merge on

##  Pandas Idiom

In [97]:
print(df.drop(df[df['Quantity'] == 0].index).rename(columns={'Weight': 'Weight (oz.)'}))

KeyError: 'Quantity'

In [98]:
f=(df.drop(df[df['Quantity']==0].index))

KeyError: 'Quantity'

In [ ]:
f=Category  Quantity  Weight
Item                                             
Pack                       Pack         1    33.0
Tent                    Shelter         1    80.0
Sleeping Pad              Sleep         0    27.0
Sleeping Bag              Sleep         1    20.0
Toothbrush/Toothpaste    Health         1     2.0
Sunscreen                Health         1     5.0
Medical Kit              Health         1     3.7
Spoon                   Kitchen         0     0.7
Stove                   Kitchen         1    20.0
Water Filter            Kitchen         1     1.8
Water Bottles           Kitchen         2    35.0
Pack Liner              Utility         1     1.0
Stuff Sack              Utility         0     1.0
Trekking Poles          Utility         1    16.0
Rain Poncho            Clothing         0     6.0
Shoes                  Clothing         1    12.0
Hat                    Clothing         1     2.5

In [2]:
# Panda Idioms Practice 2

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('census.csv')

In [6]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [30]:
df['STNAME'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [35]:
df1=(df.where(df['STNAME']=='Alabama'))
df1

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40.0,3.0,6.0,1.0,0.0,Alabama,Alabama,4779736.0,4780127.0,4785161.0,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50.0,3.0,6.0,1.0,1.0,Alabama,Autauga County,54571.0,54571.0,54660.0,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50.0,3.0,6.0,1.0,3.0,Alabama,Baldwin County,182265.0,182265.0,183193.0,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50.0,3.0,6.0,1.0,5.0,Alabama,Barbour County,27457.0,27457.0,27341.0,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50.0,3.0,6.0,1.0,7.0,Alabama,Bibb County,22915.0,22919.0,22861.0,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50.0,3.0,6.0,1.0,9.0,Alabama,Blount County,57322.0,57322.0,57373.0,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50.0,3.0,6.0,1.0,11.0,Alabama,Bullock County,10914.0,10915.0,10887.0,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50.0,3.0,6.0,1.0,13.0,Alabama,Butler County,20947.0,20946.0,20944.0,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50.0,3.0,6.0,1.0,15.0,Alabama,Calhoun County,118572.0,118586.0,118437.0,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50.0,3.0,6.0,1.0,17.0,Alabama,Chambers County,34215.0,34170.0,34098.0,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50.0,3.0,6.0,1.0,19.0,Alabama,Cherokee County,25989.0,25986.0,25976.0,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50.0,3.0,6.0,1.0,21.0,Alabama,Chilton County,43643.0,43631.0,43665.0,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50.0,3.0,6.0,1.0,23.0,Alabama,Choctaw County,13859.0,13858.0,13841.0,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50.0,3.0,6.0,1.0,25.0,Alabama,Clarke County,25833.0,25840.0,25767.0,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50.0,3.0,6.0,1.0,27.0,Alabama,Clay County,13932.0,13932.0,13880.0,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50.0,3.0,6.0,1.0,29.0,Alabama,Cleburne County,14972.0,14972.0,14973.0,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50.0,3.0,6.0,1.0,31.0,Alabama,Coffee County,49948.0,49948.0,50177.0,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50.0,3.0,6.0,1.0,33.0,Alabama,Colbert County,54428.0,54428.0,54514.0,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50.0,3.0,6.0,1.0,35.0,Alabama,Conecuh County,13228.0,13228.0,13208.0,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50.0,3.0,6.0,1.0,37.0,Alabama,Coosa County,11539.0,11758.0,11758.0,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50.0,3.0,6.0,1.0,39.0,Alabama,Covington County,37765.0,37765.0,37796.0,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
21,50.0,3.0,6.0,1.0,41.0,Alabama,Crenshaw County,13906.0,13906.0,13853.0,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
22,50.0,3.0,6.0,1.0,43.0,Alabama,Cullman County,80406.0,80410.0,80473.0,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
23,50.0,3.0,6.0,1.0,45.0,Alabama,Dale County,50251.0,50251.0,50358.0,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
24,50.0,3.0,6.0,1.0,47.0,Alabama,Dallas County,43820.0,43820.0,43803.0,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
25,50.0,3.0,6.0,1.0,49.0,Alabama,DeKalb County,71109.0,71115.0,71142.0,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
26,50.0,3.0,6.0,1.0,51.0,Alabama,Elmore County,79303.0,79296.0,79465.0,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
27,50.0,3.0,6.0,1.0,53.0,Alabama,Escambia County,38319.0,38319.0,38309.0,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
28,50.0,3.0,6.0,1.0,55.0,Alabama,Etowah County,104430.0,104427.0,104442.0,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
29,50.0,3.0,6.0,1.0,57.0,Alabama,Fayette County,17241.0,17241.0,17231.0,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3168,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3171,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3174,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3182,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3183,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3186,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
import numpy as np
np.average(df1['CENSUS2010POP'])

nan

In [37]:
df2=df1.dropna()
df2

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40.0,3.0,6.0,1.0,0.0,Alabama,Alabama,4779736.0,4780127.0,4785161.0,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50.0,3.0,6.0,1.0,1.0,Alabama,Autauga County,54571.0,54571.0,54660.0,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50.0,3.0,6.0,1.0,3.0,Alabama,Baldwin County,182265.0,182265.0,183193.0,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50.0,3.0,6.0,1.0,5.0,Alabama,Barbour County,27457.0,27457.0,27341.0,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50.0,3.0,6.0,1.0,7.0,Alabama,Bibb County,22915.0,22919.0,22861.0,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50.0,3.0,6.0,1.0,9.0,Alabama,Blount County,57322.0,57322.0,57373.0,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50.0,3.0,6.0,1.0,11.0,Alabama,Bullock County,10914.0,10915.0,10887.0,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50.0,3.0,6.0,1.0,13.0,Alabama,Butler County,20947.0,20946.0,20944.0,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50.0,3.0,6.0,1.0,15.0,Alabama,Calhoun County,118572.0,118586.0,118437.0,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50.0,3.0,6.0,1.0,17.0,Alabama,Chambers County,34215.0,34170.0,34098.0,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50.0,3.0,6.0,1.0,19.0,Alabama,Cherokee County,25989.0,25986.0,25976.0,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50.0,3.0,6.0,1.0,21.0,Alabama,Chilton County,43643.0,43631.0,43665.0,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50.0,3.0,6.0,1.0,23.0,Alabama,Choctaw County,13859.0,13858.0,13841.0,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50.0,3.0,6.0,1.0,25.0,Alabama,Clarke County,25833.0,25840.0,25767.0,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50.0,3.0,6.0,1.0,27.0,Alabama,Clay County,13932.0,13932.0,13880.0,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50.0,3.0,6.0,1.0,29.0,Alabama,Cleburne County,14972.0,14972.0,14973.0,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50.0,3.0,6.0,1.0,31.0,Alabama,Coffee County,49948.0,49948.0,50177.0,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50.0,3.0,6.0,1.0,33.0,Alabama,Colbert County,54428.0,54428.0,54514.0,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50.0,3.0,6.0,1.0,35.0,Alabama,Conecuh County,13228.0,13228.0,13208.0,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50.0,3.0,6.0,1.0,37.0,Alabama,Coosa County,11539.0,11758.0,11758.0,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50.0,3.0,6.0,1.0,39.0,Alabama,Covington County,37765.0,37765.0,37796.0,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
21,50.0,3.0,6.0,1.0,41.0,Alabama,Crenshaw County,13906.0,13906.0,13853.0,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
22,50.0,3.0,6.0,1.0,43.0,Alabama,Cullman County,80406.0,80410.0,80473.0,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
23,50.0,3.0,6.0,1.0,45.0,Alabama,Dale County,50251.0,50251.0,50358.0,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
24,50.0,3.0,6.0,1.0,47.0,Alabama,Dallas County,43820.0,43820.0,43803.0,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
25,50.0,3.0,6.0,1.0,49.0,Alabama,DeKalb County,71109.0,71115.0,71142.0,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
26,50.0,3.0,6.0,1.0,51.0,Alabama,Elmore County,79303.0,79296.0,79465.0,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
27,50.0,3.0,6.0,1.0,53.0,Alabama,Escambia County,38319.0,38319.0,38309.0,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
28,50.0,3.0,6.0,1.0,55.0,Alabama,Etowah County,104430.0,104427.0,104442.0,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
29,50.0,3.0,6.0,1.0,57.0,Alabama,Fayette County,17241.0,17241.0,17231.0,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,50.0,3.0,6.0,1.0,75.0,Alabama,Lamar County,14564.0,14564.0,14495.0,...,-10.004516,-0.560538,0.281304,-4.674718,-7.588774,-9.865564,-0.490471,0.351630,-4.603889,-7.517182
39,50.0,3.0,6.0,1.0,77.0,Alabama,Lauderdale County,92709.0,92709.0,92747.0,...,0.064737,1.640601,1.952440,5.113245,-4.782962,0.593424,2.039957,2.373132,5.597658,-4.308975
40,50.0,3.0,6.0,1.0,79.0,Alabama,Lawrence County,34339.0,34339.0,34305.0,...,-5.530358,-7.785199,-6.088235,-1.850940,-7.604334,-5.501097,-7.667242,-5.969440,-1.731524,-7.484108
41,50.0,3.0,6.0,1.0,81.0,Alabama,Lee County,140247.0,140296.0,140782.0,...,13.479880,16.576137,14.902891,9.198122,6.255238,17.060473,20.343441,18.496685,13.015964,10.134256
42,50.0,3.0,6.0,1.0,83.0,Alabama,Limestone County,82782.0,82782.0,83163.0,...,22.558084,16.312081,12.838340,14.976432,6.824853,23.458985,16.971506,13.621581,15.934746,7.801399
43,50.0,3.0,6.0,1.0,85.0,Alabama,Lowndes County,11299.0,11299.0,11275.0,...,-13.575065,-28.401074,-11.493720,-16.071429,-7.804692,-13.485755,-28.310045,-11.401029,-15.883459,-7.614334
44,50.0,3.0,6.0,1.0,87.0,Alabama,Macon County,21452.0,21448.0,21545.0,...,-11.725137,-38.373096,-28.414867,-20.642728,-10.599605,-12.005419,-38.421002,-28.464457,-20.642728,-10.599605
45,50.0,3.0,6.0,1.0,89.0,Alabama,Madison County,334811.0,334811.0,336138.0,...,4.170416,3.438521,6.367708,4.064107,2.480087,5.739131,4.880766,7.818211,5.734524,4.180881
46,50.0,3.0,6.0,1.0,91.0,Alabama,Marengo County,21027.0,21029.0,20942.0,...,-12.484994,-15.404427,-11.313608,-4.808407,-8.315905,-11.572629,-14.286756,-10.133058,-3.420413,-6.921621
47,50.0,3.0,6.0,1.0,93.0,Alabama,Marion County,30776.0,30777.0,30800.0,...,0.877663,-4.278110,-5.066373,1.420924,-0.033105,1.527785,-3.853565,-4.605793,1.916595,0.463469
48,50.0,3.0,6.0,1.0,95.0,Alabama,Marshall County,93019.0,93019.0,93146.0,...,3.838505,0.287029,-1.039209,-2.246560,0.423099,5.249877,1.009918,-0.148458,-1.155071,1.533734
49,50.0,3.0,6.0,1.0,97.0,Alabama,Mobile County,412992.0,413143.0,413332.0,...,-5.242052,-3.722733,-3.181655,-2.311087,-3.873201,-3.751237,-2.281051,-1.753896,-0.759909,-2.288272
50,50.0,3.0,6.0,1.0,99.0,Alabama,Monroe County,23068.0,23070.0,22982.0,...,-8.697933,-6.613611,-17.389749,-10.669451,-5.967409,-8.697933,-6.613611,-17.389749,-10.669451,-5.967409
51,50.0,3.0,6.0,1.0,101.0,Alabama,Montgomery County,229363.0,229363.0,229723.0,...,0.793549,-17.053618,-16.353778,-8.910671,-5.820167,2.441356,-15.057012,-14.486528,-6.784461,-3.598965
52,50.0,3.0,6.0,1.0,103.0,Alabama,Morgan County,119490.0,119486.0,119603.0,...,-0.058443,-0.616520,-6.114295,-1.997409,-3.670246,0.993538,0.024994,-5.288490,-1.036313,-2.700432
53,50.0,3.0,6.0,1.0,105.0,Alabama,Perry County,10591.0,10581.0,10540.0,...,-4.275534,-30.449493,-13.879939,-11.386538,-16.096786,-3.895487,-30.256162,-13.582511,-11.185006,-15.891731
54,50.0,3.0,6.0,1.0,107.0,Alabama,Pickens County,19746.0,19746.0,19716.0,...,-16.788228,0.723253,2.995868,47.451138,24.852559,-16.788228,0.723253,2.995868,47.451138,24.852559
55,50.0,3.0,6.0,1.0,109.0,Alabama,Pike County,32899.0,32899.0,32957.0,...,-6.316429,0.333293,11.688020,-21.462830,-6.290069,-3.735196,3.211732,14.804825,-17.865707,-2.661183
56,50.0,3.0,6.0,1.0,111.0,Alabama,Randolph County,22913.0,22914.0,22891.0,...,-2.232289,-6.867709,1.016395,-5.275290,9.959718,-2.407371,-7.131851,0.795439,-5.496941,9.738391
57,50.0,3.0,6.0,1.0,113.0,Alabama,Russell County,52947.0,52951.0,53297.0,...,24.111089,42.595881,22.802470,-1.728057,-6.232617,24.222029,44.584517,23.569942,-1.107299,-5.193848
58,50.0,3.0,6.0,1.0,115.0,Alabama,St. Clair County,83593.0,83593.0,83812.0,...,1.498849,6.643969,9.511583,1.551186,3.121490,2.093630,7.104209,10.013421,2.118411,3.685893
59,50.0,3.0,6.0,1.0,117.0,Alabama,Shelby County,195085.0,195218.0,196048.0,...,1.456731,7.783057,8.805327,5.037501,5.986812,3.065733,8.755939,9.897345,6.359052,7.307574
60,50.0,3.0,6.0,1.0,119.0,Alabama,Sumter County,13763.0,13763.0,13740.0,...,-16.368174,-4.006083,-4.990131,-13.135673,-12.981098,-15.120376,-2.225602,-3.053663,-10.958904,-10.855538
61,50.0,3.0,6.0,1.0,121.0,Alabama,Talladega County,82291.0,82291.0,82071.0,...,-2.318600,1.563340,-5.966492,1.230224,-4.231434,-1.879286,2.064097,-5.402922,1.919150,-3.540587
62,50.0,3.0,6.0,1.0,123.0,Alabama,Tallapoosa County,41616.0,41618.0,41502.0,...,-0.337532,-6.705723,1.772834,-0.194404,-5.978818,0.072328,-6.415222,2.088545,0.218704,-5.515154
63,50.0,3.0,6.0,1.0,125.0,Alabama,Tuscaloosa County,194656.0,194653.0,194977.0,...,3.983504,4.256278,5.261075,4.787490,1.884402,5.306232,5.202679,6.333332,6.057539,3.158710
64,50.0,3.0,6.0,1.0,127.0,Alabama,Walker County,67023.0,67023.0,67004.0,...,-4.579296,-4.336533,-0.666096,-3.300481,-3.087245,-4.085450,-3.869753,-0.181663,-2.692097,-2.460626
65,50.0,3.0,6.0,1.0,129.0,Alabama,Washington County,17581.0,17583.0,17610.0,...,-14.708407,-13.062030,-11.181733,1.067236,-0.950486,-13.849940,-12.075121,-10.122411,2.193763,0.118811
66,50.0,3.0,6.0,1.0,131.0,Alabama,Wilcox County,11670.0,11665.0,11557.0,...,-7.029724,-10.239356,-12.314507,-13.835235,0.090453,-7.029724,-10.239356,-12.314507,-13.835235,0.090453
67,50.0,3.0,6.0,1.0,133.0,Alabama,Winston County,24484.0,24483.0,24401.0,...,0.410332,-3.916234,2.441548,1.077609,-6.669724,0.410332,-3.957457,2.400166,1.036162,-6.711409

In [39]:
np.average(df2['CENSUS2010POP'])

140580.4705882353

In [64]:
%%timeit -n 10

for state in df['STNAME'].unique():
    df1=(df.where(df['STNAME']==state))
    df2=df1.dropna()
    avg=np.average(df2['CENSUS2010POP'])
    print("The average population in " +  state + " is "+ str(avg))

The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714

The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0

The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0

The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098

The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667

The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667

The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811

The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444

The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182

The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369

The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048

The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552

The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369

The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225

The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182

The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182

The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617

The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048

The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235

The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529

The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923

The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763

The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111

The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
The average population in Alabama is 140580.4705882353
The average population in Alaska is 47348.73333333333
The average population in Arizona is 799002.125
The average population in Arkansas is 76734.68421052632
The average population in California is 1262845.9661016949
The average population in Colorado is 154744.4923076923
The average population in Connecticut is 794243.7777777778
The average population in Delaware is 448967.0
The average population in District of Columbia is 601723.0
The average population in Florida is 552979.7058823529
The average population in Georgia is 121095.6625
The average population in Hawaii is 453433.6666666667
The average population in Idaho is 69670.3111111111
The average population in Illinois is 249138.4854368932
The average population in Indiana is 139436.60215053763
The average population in Iowa is 60927.1
The average population in Kansas is 53832.41509433962
The average population in Kentucky is 71725.07438016529
The average population in Louisiana is 139488.36923076923
The average population in Maine is 156277.76470588235
The average population in Maryland is 461884.16
The average population in Massachusetts is 873017.2
The average population in Michigan is 235324.7619047619
The average population in Minnesota is 120543.75
The average population in Mississippi is 71501.13253012048
The average population in Missouri is 103257.36206896552
The average population in Montana is 34716.31578947369
The average population in Nebraska is 38858.31914893617
The average population in Nevada is 300061.22222222225
The average population in New Hampshire is 239358.18181818182
The average population in New Jersey is 799263.0909090909
The average population in New Mexico is 121128.17647058824
The average population in New York is 615177.8412698413
The average population in North Carolina is 188821.44554455444
The average population in North Dakota is 24910.777777777777
The average population in Ohio is 259247.2808988764
The average population in Oklahoma is 96188.48717948717
The average population in Oregon is 207085.0810810811
The average population in Pennsylvania is 373599.3823529412
The average population in Rhode Island is 350855.6666666667
The average population in South Carolina is 196824.0
The average population in South Dakota is 24303.880597014926
The average population in Tennessee is 132210.52083333334
The average population in Texas is 197220.0862745098
The average population in Utah is 184259.0
The average population in Vermont is 83432.13333333333
The average population in Virginia is 119371.83582089552
The average population in Washington is 336227.0
The average population in West Virginia is 66178.35714285714
The average population in Wisconsin is 155807.83561643836
The average population in Wyoming is 46968.833333333336
1.44 s ± 71.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [49]:
df01=df.groupby('STNAME')['CENSUS2010POP']
# np.average(df01)

In [79]:
%%timeit -n 10

for group,frame in df.groupby('STNAME'):
    avg=np.average(frame['CENSUS2010POP'])
    print("The average population in " + group+" is " +str(avg))
#     print("++++++++++++++++++++++++++++++++++++++++++++")

The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256

The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875

The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2

The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2

The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667
The average population in Louisiana is 70833.9375
The average population in Maine is 83022.5625
The average population in Maryland is 240564.66666666666
The average population in Massachusetts is 467687.78571428574
The average population in Michigan is 119080.0
The average population in Minnesota is 60964.65517241379
The average population in Mississippi is 36186.54878048781
The average population in Missouri is 52077.62608695652
The average population in Montana is 17668.125
The average population in Nebraska is 19638.075268817203
The average population in Nevada is 158855.9411764706
The average population in New Hampshire is 131647.0
The average population in New Jersey is 418661.61904761905
The average population in New Mexico is 62399.36363636364
The average population in New York is 312550.03225806454
The average population in North Carolina is 95354.83
The average population in North Dakota is 12690.396226415094
The average population in Ohio is 131096.63636363635
The average population in Oklahoma is 48718.844155844155
The average population in Oregon is 106418.72222222222
The average population in Pennsylvania is 189587.74626865672
The average population in Rhode Island is 210513.4
The average population in South Carolina is 100551.39130434782
The average population in South Dakota is 12336.060606060606
The average population in Tennessee is 66801.1052631579
The average population in Texas is 98998.27165354331
The average population in Utah is 95306.37931034483
The average population in Vermont is 44695.78571428572
The average population in Virginia is 60111.29323308271
The average population in Washington is 172424.10256410256
The average population in West Virginia is 33690.8
The average population in Wisconsin is 78985.91666666667
The average population in Wyoming is 24505.478260869564
The average population in Alabama is 71339.34328358209
The average population in Alaska is 24490.724137931036
The average population in Arizona is 426134.4666666667
The average population in Arkansas is 38878.90666666667
The average population in California is 642309.5862068966
The average population in Colorado is 78581.1875
The average population in Connecticut is 446762.125
The average population in Delaware is 299311.3333333333
The average population in District of Columbia is 601723.0
The average population in Florida is 280616.5671641791
The average population in Georgia is 60928.63522012578
The average population in Hawaii is 272060.2
The average population in Idaho is 35626.86363636364
The average population in Illinois is 125790.50980392157
The average population in Indiana is 70476.10869565218
The average population in Iowa is 30771.262626262625
The average population in Kansas is 27172.55238095238
The average population in Kentucky is 36161.39166666667

In [62]:
avg

46968.833333333336

In [66]:
for group,frame in df.groupby('STNAME'):
    print(group)

Alabama
Alaska
Arizona
Arkansas
California
Colorado
Connecticut
Delaware
District of Columbia
Florida
Georgia
Hawaii
Idaho
Illinois
Indiana
Iowa
Kansas
Kentucky
Louisiana
Maine
Maryland
Massachusetts
Michigan
Minnesota
Mississippi
Missouri
Montana
Nebraska
Nevada
New Hampshire
New Jersey
New Mexico
New York
North Carolina
North Dakota
Ohio
Oklahoma
Oregon
Pennsylvania
Rhode Island
South Carolina
South Dakota
Tennessee
Texas
Utah
Vermont
Virginia
Washington
West Virginia
Wisconsin
Wyoming


## GROUPBY FUNCTION

In [73]:
df=df.set_index('STNAME')
df

KeyError: 'STNAME'

In [69]:
def fun(item):
    if item[0]<'M':
        return 0
    if item[0]<'Q':
        return 1
    return 2

In [78]:
for group, frame in df.groupby(fun):
    print("There are"+ str(len(frame))+'records in group' + str(group))

TypeError: 'int' object is not subscriptable

In [74]:
df=pd.read_csv('census.csv')
df=df[df['SUMLEV']==50]

In [75]:
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43665,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13841,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50,3,6,1,25,Alabama,Clarke County,25833,25840,25767,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13880,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14973,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50177,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54514,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13208,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37796,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
21,50,3,6,1,41,Alabama,Crenshaw County,13906,13906,13853,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
22,50,3,6,1,43,Alabama,Cullman County,80406,80410,80473,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
23,50,3,6,1,45,Alabama,Dale County,50251,50251,50358,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
24,50,3,6,1,47,Alabama,Dallas County,43820,43820,43803,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
25,50,3,6,1,49,Alabama,DeKalb County,71109,71115,71142,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
26,50,3,6,1,51,Alabama,Elmore County,79303,79296,79465,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
27,50,3,6,1,53,Alabama,Escambia County,38319,38319,38309,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
28,50,3,6,1,55,Alabama,Etowah County,104430,104427,104442,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
29,50,3,6,1,57,Alabama,Fayette County,17241,17241,17231,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
30,50,3,6,1,59,Alabama,Franklin County,31704,31709,31734,...,-1.638750,-5.459394,-8.043702,-1.267849,-2.401719,0.063029,-3.471291,-5.700261,1.553115,0.442422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,50,2,3,55,129,Wisconsin,Washburn County,15911,15911,15930,...,-6.873936,7.338289,-6.732724,3.510452,-5.123279,-6.747809,7.464811,-6.605691,3.638104,-4.995197
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,-0.765799,2.128860,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,3.111756,-2.241873,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,4.930022,-2.404973,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.316712,2.889873,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-4.081523,-5.019090,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7114,...,-1.544618,-4.202564,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,2.747083,7.782673,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13408,...,14.293649,3.961413,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,3.322604,6.208609,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,4.995063,-4.058912,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18091,...,-9.802564,-11.566801,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,-0.401849,0.806452,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28259,...,4.582951,8.057765,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8678,...,4.373094,5.392073,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,0.958559,8.425487,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10244,...,-23.741784,15.272374,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

## APPLYING GROUPBY

In [76]:
df.groupby('STNAME').agg({'CENSUS2010POP':np.average})

                      CENSUS2010POP
STNAME
Alabama                71339.343284
Alaska                 24490.724138
Arizona               426134.466667
Arkansas               38878.906667
California            642309.586207
Colorado               78581.187500
Connecticut           446762.125000
Delaware              299311.333333
District of Columbia  601723.000000
Florida               280616.567164
Georgia                60928.635220
Hawaii                272060.200000
Idaho                  35626.863636
Illinois              125790.509804
Indiana                70476.108696
Iowa                   30771.262626
Kansas                 27172.552381
Kentucky               36161.391667
Louisiana              70833.937500
Maine                  83022.562500
Maryland              240564.666667
Massachusetts         467687.785714
Michigan              119080.000000
Minnesota              60964.655172
Mississippi            36186.548780
Missouri               52077.626087
Montana                17668.125000
Nebraska               19638.075269
Nevada                158855.941176
New Hampshire         131647.000000
New Jersey            418661.619048
New Mexico             62399.363636
New York              312550.032258
North Carolina         95354.830000
North Dakota           12690.396226
Ohio                  131096.636364
Oklahoma               48718.844156
Oregon                106418.722222
Pennsylvania          189587.746269
Rhode Island          210513.400000
South Carolina        100551.391304
South Dakota           12336.060606
Tennessee              66801.105263
Texas                  98998.271654
Utah                   95306.379310
Vermont                44695.785714
Virginia               60111.293233
Washington            172424.102564
West Virginia          33690.800000
Wisconsin              78985.916667
Wyoming                24505.478261

In [ ]:
# print(df.groupby('Category').apply(lambda df,a,b: sum(df[a] * df[b]), 'Weight (oz.)', 'Quantity'))


# Or alternatively without using a lambda:
def totalweight(df, w, q):
        return sum(df[w] * df[q])
        
print(df.groupby('Category').apply(totalweight, 'Weight (oz.)', 'Quantity'))