---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [2]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='â„–':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [3]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan, dtype: object

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [10]:
df['Gold'].argmax()

'United States'

In [4]:
df['T_Gold']=df['Gold']+df['Gold.1']+df['Gold.2']
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,T_Gold
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG,0
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG,10
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG,36
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM,2
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ,6

In [5]:
df=df.sort_values('T_Gold')
df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,T_Gold
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG,0
Namibia,6,0,4,0,4,0,0,0,0,0,6,0,4,0,4,NAM,0
Montenegro,2,0,1,0,1,2,0,0,0,0,4,0,1,0,1,MNE,0
Moldova,5,0,2,5,7,6,0,0,0,0,11,0,2,5,7,MDA,0
Mauritius,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,MRI,0
Malaysia,12,0,3,3,6,0,0,0,0,0,12,0,3,3,6,MAS,0
Macedonia,5,0,0,1,1,5,0,0,0,0,10,0,0,1,1,MKD,0
Netherlands Antilles,13,0,1,0,1,2,0,0,0,0,15,0,1,0,1,AHO,0
Lebanon,16,0,2,2,4,16,0,0,0,0,32,0,2,2,4,LIB,0
Iraq,13,0,0,1,1,0,0,0,0,0,13,0,0,1,1,IRQ,0
Iceland,19,0,2,2,4,17,0,0,0,0,36,0,2,2,4,ISL,0
Haiti,14,0,1,1,2,0,0,0,0,0,14,0,1,1,2,HAI,0
Guyana,16,0,0,1,1,0,0,0,0,0,16,0,0,1,1,GUY,0
Guatemala,13,0,1,0,1,1,0,0,0,0,14,0,1,0,1,GUA,0
Ghana,13,0,1,3,4,1,0,0,0,0,14,0,1,3,4,GHA,0
Kuwait,12,0,0,2,2,0,0,0,0,0,12,0,0,2,2,KUW,0
Niger,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1,NIG,0
Paraguay,11,0,1,0,1,1,0,0,0,0,12,0,1,0,1,PAR,0
Philippines,20,0,2,7,9,4,0,0,0,0,24,0,2,7,9,PHI,0
Zambia,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2,ZAM,0
Independent Olympic Participants,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3,IOP,0
Virgin Islands,11,0,1,0,1,7,0,0,0,0,18,0,1,0,1,ISV,0
Vietnam,14,0,2,0,2,0,0,0,0,0,14,0,2,0,2,VIE,0
Tonga,8,0,1,0,1,1,0,0,0,0,9,0,1,0,1,TGA,0
Togo,9,0,0,1,1,1,0,0,0,0,10,0,0,1,1,TOG,0
Tanzania,12,0,2,0,2,0,0,0,0,0,12,0,2,0,2,TAN,0
Tajikistan,5,0,1,2,3,4,0,0,0,0,9,0,1,2,3,TJK,0
Sudan,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1,SUD,0
Sri Lanka,16,0,2,0,2,0,0,0,0,0,16,0,2,0,2,SRI,0
Singapore,15,0,2,2,4,0,0,0,0,0,15,0,2,2,4,SIN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Turkey,21,39,25,24,88,16,0,0,0,0,37,39,25,24,88,TUR,78
New Zealand,22,42,18,39,99,15,0,1,0,1,37,42,19,39,100,NZL,84
Denmark,26,43,68,68,179,13,0,1,0,1,39,43,69,68,180,DEN,86
Czechoslovakia,16,49,49,45,143,16,2,8,15,25,32,51,57,60,168,TCH,102
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL,104
Unified Team,1,45,38,29,112,1,9,6,8,23,2,54,44,37,135,EUN,108
West Germany,5,56,67,81,204,6,11,15,13,39,11,67,82,94,243,FRG,134
Poland,20,64,82,125,271,22,6,7,7,20,42,70,89,132,291,POL,140
Cuba,19,72,67,70,209,0,0,0,0,0,19,72,67,70,209,CUB,144
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT,154
Romania,20,88,94,119,301,20,0,0,1,1,40,88,94,120,302,ROU,176
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI,194
South Korea,16,81,82,80,243,17,26,17,10,53,33,107,99,90,296,KOR,214
Netherlands,25,77,85,104,266,20,37,38,35,110,45,114,123,139,376,NED,228
Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,CAN,242
Japan,21,130,126,142,398,20,10,17,18,45,41,140,143,160,443,JPN,280
Finland,24,101,84,117,302,22,42,62,57,161,46,143,146,174,463,FIN,286
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS,288
Hungary,25,167,144,165,476,22,0,2,4,6,47,167,146,169,482,HUN,334
Norway,24,56,49,43,148,22,118,111,100,329,46,174,160,143,477,NOR,348
Russia,5,132,121,142,395,6,49,40,35,124,11,181,161,177,519,RUS,362
East Germany,5,153,129,127,409,6,39,36,35,110,11,192,165,162,519,GDR,384
Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,SWE,386
China,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,CHN,426
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA,466
Italy,26,198,166,185,549,22,37,34,43,114,48,235,200,228,663,ITA,470
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR,492
Germany,15,174,182,217,573,11,78,78,53,209,26,252,260,270,782,GER,504
Soviet Union,9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204,URS,946
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA,2144

In [8]:
df.iloc[-1].ID

'USA'

In [ ]:
df

In [11]:
df.max()

# Summer            27
Gold               976
Silver             757
Bronze             666
Total             2399
# Winter            22
Gold.1             118
Silver.1           111
Bronze.1           100
Total.1            329
# Games             49
Gold.2            1072
Silver.2           859
Bronze.2           750
Combined total    2681
ID                 ZZX
T_Gold            2144
dtype: object

In [35]:
#Method #1
def answer_one(df=df):
    df['T_Gold']=df['Gold']+df['Gold.1']+df['Gold.2']
    df=df.sort_values('T_Gold') 
    v=df.iloc[-1]
    return v

In [37]:
#Method #2

def answer_one():
    df['T_Gold']=df['Gold']+df['Gold.1']+df['Gold.2']
   
    return df.max()

In [38]:
answer_one()

# Summer            27
Gold               976
Silver             757
Bronze             666
Total             2399
# Winter            22
Gold.1             118
Silver.1           111
Bronze.1           100
Total.1            329
# Games             49
Gold.2            1072
Silver.2           859
Bronze.2           750
Combined total    2681
ID                 ZZX
T_Gold            2144
dtype: object

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [13]:
df['G_diff']=abs(df['Gold']-df['Gold.1'])

In [14]:
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,T_Gold,G_diff
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG,0,0
Namibia,6,0,4,0,4,0,0,0,0,0,6,0,4,0,4,NAM,0,0
Montenegro,2,0,1,0,1,2,0,0,0,0,4,0,1,0,1,MNE,0,0
Moldova,5,0,2,5,7,6,0,0,0,0,11,0,2,5,7,MDA,0,0
Mauritius,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,MRI,0,0

In [16]:
df['G_diff'].argmax()

'United States'

In [15]:
df=df.sort_values('G_diff')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,T_Gold,G_diff
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG,0,0
Tanzania,12,0,2,0,2,0,0,0,0,0,12,0,2,0,2,TAN,0,0
Tajikistan,5,0,1,2,3,4,0,0,0,0,9,0,1,2,3,TJK,0,0
Sudan,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1,SUD,0,0
Sri Lanka,16,0,2,0,2,0,0,0,0,0,16,0,2,0,2,SRI,0,0

In [63]:
df.iloc[-1]

# Summer            26
Gold               976
Silver             757
Bronze             666
Total             2399
# Winter            22
Gold.1              96
Silver.1           102
Bronze.1            84
Total.1            282
# Games             48
Gold.2            1072
Silver.2           859
Bronze.2           750
Combined total    2681
ID                 USA
G_diff             880
T_Gold            2144
Name: United States, dtype: object

In [65]:
def answer_two(df=df):
    df['G_diff']=abs(df['Gold']-df['Gold.1'])
    df.sort_values('G_diff')
    return df.iloc[-1]

answer_two()

# Summer            26
Gold               976
Silver             757
Bronze             666
Total             2399
# Winter            22
Gold.1              96
Silver.1           102
Bronze.1            84
Total.1            282
# Games             48
Gold.2            1072
Silver.2           859
Bronze.2           750
Combined total    2681
ID                 USA
G_diff             880
T_Gold            2144
Name: United States, dtype: object

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [26]:
eligible_df=df[(df['Gold']>0) & (df['Gold.1']>0)]
eligible_df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID,T_Gold,G_diff,TGold,G_diff_rel
Slovenia,6,4,6,9,19,7,2,4,9,15,13,6,10,18,34,SLO,12,2,12,0.166667
Croatia,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34,CRO,20,2,20,0.100000
Canada,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,CAN,242,3,242,0.012397
Switzerland,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,SUI,194,3,194,0.015464
Uzbekistan,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21,UZB,12,4,12,0.333333
Estonia,11,9,9,15,33,9,4,2,1,7,20,13,11,16,40,EST,26,5,26,0.192308
Slovakia,5,7,9,8,24,6,2,2,1,5,11,9,11,9,29,SVK,18,5,18,0.277778
Belarus,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,BLR,36,6,36,0.166667
Czech Republic,5,14,15,15,44,6,7,9,8,24,11,21,24,23,68,CZE,42,7,42,0.166667
Kazakhstan,5,16,17,19,52,6,1,3,3,7,11,17,20,22,59,KAZ,34,15,34,0.441176
United Team of Germany,3,28,54,36,118,3,8,6,5,19,6,36,60,41,137,EUA,72,20,72,0.277778
Ukraine,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122,UKR,70,31,70,0.442857
Spain,22,37,59,35,131,19,1,0,1,2,41,38,59,36,133,ESP,76,36,76,0.473684
Belgium,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,BEL,76,36,76,0.473684
Unified Team,1,45,38,29,112,1,9,6,8,23,2,54,44,37,135,EUN,108,36,108,0.333333
Netherlands,25,77,85,104,266,20,37,38,35,110,45,114,123,139,376,NED,228,40,228,0.175439
Austria,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,AUT,154,41,154,0.266234
West Germany,5,56,67,81,204,6,11,15,13,39,11,67,82,94,243,FRG,134,45,134,0.335821
Czechoslovakia,16,49,49,45,143,16,2,8,15,25,32,51,57,60,168,TCH,102,47,102,0.460784
Bulgaria,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,BUL,104,50,104,0.480769
South Korea,16,81,82,80,243,17,26,17,10,53,33,107,99,90,296,KOR,214,55,214,0.257009
Poland,20,64,82,125,271,22,6,7,7,20,42,70,89,132,291,POL,140,58,140,0.414286
Finland,24,101,84,117,302,22,42,62,57,161,46,143,146,174,463,FIN,286,59,286,0.206294
Norway,24,56,49,43,148,22,118,111,100,329,46,174,160,143,477,NOR,348,62,348,0.178161
Russia,5,132,121,142,395,6,49,40,35,124,11,181,161,177,519,RUS,362,83,362,0.229282
Sweden,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,SWE,386,93,386,0.240933
Germany,15,174,182,217,573,11,78,78,53,209,26,252,260,270,782,GER,504,96,504,0.190476
East Germany,5,153,129,127,409,6,39,36,35,110,11,192,165,162,519,GDR,384,114,384,0.296875
Japan,21,130,126,142,398,20,10,17,18,45,41,140,143,160,443,JPN,280,120,280,0.428571
Australia,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,AUS,288,134,288,0.465278
Italy,26,198,166,185,549,22,37,34,43,114,48,235,200,228,663,ITA,470,161,470,0.342553
France,27,202,223,246,671,22,31,31,47,109,49,233,254,293,780,FRA,466,171,466,0.366953
China,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,CHN,426,189,426,0.443662
Great Britain,27,236,272,272,780,22,10,4,12,26,49,246,276,284,806,GBR,492,226,492,0.459350
Soviet Union,9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204,URS,946,317,946,0.335095
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA,2144,880,2144,0.410448

In [29]:
# ANSWER 3

eligible_df=df[(df['Gold']>0) & (df['Gold.1']>0)]
eligible_df['G_diff_rel']=abs(eligible_df['Gold']-eligible_df['Gold.1'])/eligible_df['T_Gold']
eligible_df['G_diff_rel'].argmax()

C:\Users\wlaik\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

'Bulgaria'

In [19]:
df['G_diff_rel'].argmax()

'Armenia'

In [21]:
def answer_three(df=df):
    eligible_df=df[(df['Gold']>0) & (df['Gold.1']>0)]
#     df['TGold']=df['Gold']+df['Gold.1']+df['Gold.2']
    df['G_diff_rel]=abs(df['Gold']-df['Gold.1']) /eligible_df['T_Gold']
    df['G_diff_rel'].argmax()

answer_three()

SyntaxError: invalid syntax (<ipython-input-21-b5ba2817ae90>, line 4)

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created, with the country names as indices.

*This function should return a Series named `Points` of length 146*

In [54]:
df['T_Gold']=df['Gold']+df['Gold.1']+df['Gold.2']
df['T_Silver']=df['Silver']+df['Silver.1']+df['Silver.2']
df['T_Bronze']=df['Bronze']+df['Bronze.1']+df['Bronze.2']
df['df_T_combined']=df['T_Gold']+df['T_Silver']+df['T_Bronze']
df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,...,Bronze.2,Combined total,ID,T_Gold,G_diff,TGold,G_diff_rel,T_Silver,T_Bronze,df_T_combined
Afghanistan,13,0,0,2,2,0,0,0,0,0,...,2,2,AFG,0,0,0,NaN,0,4,4
Tanzania,12,0,2,0,2,0,0,0,0,0,...,0,2,TAN,0,0,0,NaN,4,0,4
Tajikistan,5,0,1,2,3,4,0,0,0,0,...,2,3,TJK,0,0,0,NaN,2,4,6
Sudan,11,0,1,0,1,0,0,0,0,0,...,0,1,SUD,0,0,0,NaN,2,0,2
Sri Lanka,16,0,2,0,2,0,0,0,0,0,...,0,2,SRI,0,0,0,NaN,4,0,4
Singapore,15,0,2,2,4,0,0,0,0,0,...,2,4,SIN,0,0,0,NaN,4,4,8
Senegal,13,0,1,0,1,5,0,0,0,0,...,0,1,SEN,0,0,0,NaN,2,0,2
Saudi Arabia,10,0,1,2,3,0,0,0,0,0,...,2,3,KSA,0,0,0,NaN,2,4,6
Qatar,8,0,0,4,4,0,0,0,0,0,...,4,4,QAT,0,0,0,NaN,0,8,8
Puerto Rico,17,0,2,6,8,6,0,0,0,0,...,6,8,PUR,0,0,0,NaN,4,12,16
Togo,9,0,0,1,1,1,0,0,0,0,...,1,1,TOG,0,0,0,NaN,0,2,2
Gabon,9,0,1,0,1,0,0,0,0,0,...,0,1,GAB,0,0,0,NaN,2,0,2
Kyrgyzstan,5,0,1,2,3,6,0,0,0,0,...,2,3,KGZ,0,0,0,NaN,2,4,6
Bohemia,3,0,1,3,4,0,0,0,0,0,...,3,4,BOH,0,0,0,NaN,2,6,8
Barbados,11,0,0,1,1,0,0,0,0,0,...,1,1,BAR,0,0,0,NaN,0,2,2
Djibouti,7,0,0,1,1,0,0,0,0,0,...,1,1,DJI,0,0,0,NaN,0,2,2
Bermuda,17,0,0,1,1,7,0,0,0,0,...,1,1,BER,0,0,0,NaN,0,2,2
Botswana,9,0,1,0,1,0,0,0,0,0,...,0,1,BOT,0,0,0,NaN,2,0,2
Cyprus,9,0,1,0,1,10,0,0,0,0,...,0,1,CYP,0,0,0,NaN,2,0,2
British West Indies,1,0,0,2,2,0,0,0,0,0,...,2,2,BWI,0,0,0,NaN,0,4,4
Ivory Coast,12,0,1,0,1,0,0,0,0,0,...,0,1,CIV,0,0,0,NaN,2,0,2
Eritrea,4,0,0,1,1,0,0,0,0,0,...,1,1,ERI,0,0,0,NaN,0,2,2
Tonga,8,0,1,0,1,1,0,0,0,0,...,0,1,TGA,0,0,0,NaN,2,0,2
Bahrain,8,0,0,1,1,0,0,0,0,0,...,1,1,BRN,0,0,0,NaN,0,2,2
Virgin Islands,11,0,1,0,1,7,0,0,0,0,...,0,1,ISV,0,0,0,NaN,2,0,2
Namibia,6,0,4,0,4,0,0,0,0,0,...,0,4,NAM,0,0,0,NaN,8,0,8
Montenegro,2,0,1,0,1,2,0,0,0,0,...,0,1,MNE,0,0,0,NaN,2,0,2
Moldova,5,0,2,5,7,6,0,0,0,0,...,5,7,MDA,0,0,0,NaN,4,10,14
Mauritius,8,0,0,1,1,0,0,0,0,0,...,1,1,MRI,0,0,0,NaN,0,2,2
Malaysia,12,0,3,3,6,0,0,0,0,0,...,3,6,MAS,0,0,0,NaN,6,6,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Spain,22,37,59,35,131,19,1,0,1,2,...,36,133,ESP,76,36,76,0.473684,118,72,266
Belgium,25,37,52,53,142,20,1,1,3,5,...,56,147,BEL,76,36,76,0.473684,106,112,294
Unified Team,1,45,38,29,112,1,9,6,8,23,...,37,135,EUN,108,36,108,0.333333,88,74,270
Turkey,21,39,25,24,88,16,0,0,0,0,...,24,88,TUR,78,39,78,0.500000,50,48,176
Netherlands,25,77,85,104,266,20,37,38,35,110,...,139,376,NED,228,40,228,0.175439,246,278,752
Austria,26,18,33,35,86,22,59,78,81,218,...,116,304,AUT,154,41,154,0.266234,222,232,608
New Zealand,22,42,18,39,99,15,0,1,0,1,...,39,100,NZL,84,42,84,0.500000,38,78,200
Denmark,26,43,68,68,179,13,0,1,0,1,...,68,180,DEN,86,43,86,0.500000,138,136,360
West Germany,5,56,67,81,204,6,11,15,13,39,...,94,243,FRG,134,45,134,0.335821,164,188,486
Czechoslovakia,16,49,49,45,143,16,2,8,15,25,...,60,168,TCH,102,47,102,0.460784,114,120,336
Bulgaria,19,51,85,78,214,19,1,2,3,6,...,81,220,BUL,104,50,104,0.480769,174,162,440
South Korea,16,81,82,80,243,17,26,17,10,53,...,90,296,KOR,214,55,214,0.257009,198,180,592
Poland,20,64,82,125,271,22,6,7,7,20,...,132,291,POL,140,58,140,0.414286,178,264,582
Finland,24,101,84,117,302,22,42,62,57,161,...,174,463,FIN,286,59,286,0.206294,292,348,926
Norway,24,56,49,43,148,22,118,111,100,329,...,143,477,NOR,348,62,348,0.178161,320,286,954
Cuba,19,72,67,70,209,0,0,0,0,0,...,70,209,CUB,144,72,144,0.500000,134,140,418
Russia,5,132,121,142,395,6,49,40,35,124,...,177,519,RUS,362,83,362,0.229282,322,354,1038
Romania,20,88,94,119,301,20,0,0,1,1,...,120,302,ROU,176,88,176,0.500000,188,240,604
Sweden,26,143,164,176,483,22,50,40,54,144,...,230,627,SWE,386,93,386,0.240933,408,460,1254
Germany,15,174,182,217,573,11,78,78,53,209,...,270,782,GER,504,96,504,0.190476,520,540,1564
East Germany,5,153,129,127,409,6,39,36,35,110,...,162,519,GDR,384,114,384,0.296875,330,324,1038
Japan,21,130,126,142,398,20,10,17,18,45,...,160,443,JPN,280,120,280,0.428571,286,320,886
Australia,25,139,152,177,468,18,5,3,4,12,...,181,480,AUS,288,134,288,0.465278,310,362,960
Italy,26,198,166,185,549,22,37,34,43,114,...,228,663,ITA,470,161,470,0.342553,400,456,1326
Hungary,25,167,144,165,476,22,0,2,4,6,...,169,482,HUN,334,167,334,0.500000,292,338,964
France,27,202,223,246,671,22,31,31,47,109,...,293,780,FRA,466,171,466,0.366953,508,586,1560
China,9,201,146,126,473,10,12,22,19,53,...,145,526,CHN,426,189,426,0.443662,336,290,1052
Great Britain,27,236,272,272,780,22,10,4,12,26,...,284,806,GBR,492,226,492,0.459350,552,568,1612
Soviet Union,9,395,319,296,1010,9,78,57,59,194,...,355,1204,URS,946,317,946,0.335095,752,710,2408
United States,26,976,757,666,2399,22,96,102,84,282,...,750,2681,USA,2144,880,2144,0.410448,1718,1500,5362

In [53]:
Points=df['T_Gold']*3 +df['T_Silver']*2+df['T_Bronze']*1
Points

Afghanistan                4
Tanzania                   8
Tajikistan                 8
Sudan                      4
Sri Lanka                  8
Singapore                 12
Senegal                    4
Saudi Arabia               8
Qatar                      8
Puerto Rico               20
Togo                       2
Gabon                      4
Kyrgyzstan                 8
Bohemia                   10
Barbados                   2
Djibouti                   2
Bermuda                    2
Botswana                   4
Cyprus                     4
British West Indies        4
Ivory Coast                4
Eritrea                    2
Tonga                      4
Bahrain                    2
Virgin Islands             4
Namibia                   16
Montenegro                 4
Moldova                   18
Mauritius                  2
Malaysia                  18
                       ...
Spain                    536
Belgium                  552
Unified Team             574
Turkey                   382
Netherlands             1454
Austria                 1138
New Zealand              406
Denmark                  670
West Germany             918
Czechoslovakia           654
Bulgaria                 822
South Korea             1218
Poland                  1040
Finland                 1790
Norway                  1970
Cuba                     840
Russia                  2084
Romania                 1144
Sweden                  2434
Germany                 3092
East Germany            2136
Japan                   1732
Australia               1846
Italy                   2666
Hungary                 1924
France                  3000
China                   2240
Great Britain           3148
Soviet Union            5052
United States          11368
Length: 146, dtype: int64

In [35]:
Points.index

Index(['Afghanistan', 'Tanzania', 'Tajikistan', 'Sudan', 'Sri Lanka',
       'Singapore', 'Senegal', 'Saudi Arabia', 'Qatar', 'Puerto Rico',
       ...
       'East Germany', 'Japan', 'Australia', 'Italy', 'Hungary', 'France',
       'China', 'Great Britain', 'Soviet Union', 'United States'],
      dtype='object', length=146)

In [36]:
type(Points)

pandas.core.series.Series

In [79]:
def answer_four(df=df):
    Points=df['Gold.2']*3 +df['Silver.2']*2+df['Bronze.2']*1
    return Points

In [68]:
import numpy as np
def answer_four():
     """
     Creates weighted points based on medals
       * Gold: 3 points
       * Silver: 2 points
       * Bronze: 1 point

     Returns
     -------

     Series: column of points for each NOC
     """
     points = np.zeros(len(df))
     points += df.T_Gold * 3
     points += df.T_Silver * 2
     points += df.T_Bronze
     return pd.Series(points, index=df.index)

points = answer_four()

assert points.loc["United States"] == 5684

AssertionError:

In [69]:
answer_four()

Afghanistan                4.0
Tanzania                   8.0
Tajikistan                 8.0
Sudan                      4.0
Sri Lanka                  8.0
Singapore                 12.0
Senegal                    4.0
Saudi Arabia               8.0
Qatar                      8.0
Puerto Rico               20.0
Togo                       2.0
Gabon                      4.0
Kyrgyzstan                 8.0
Bohemia                   10.0
Barbados                   2.0
Djibouti                   2.0
Bermuda                    2.0
Botswana                   4.0
Cyprus                     4.0
British West Indies        4.0
Ivory Coast                4.0
Eritrea                    2.0
Tonga                      4.0
Bahrain                    2.0
Virgin Islands             4.0
Namibia                   16.0
Montenegro                 4.0
Moldova                   18.0
Mauritius                  2.0
Malaysia                  18.0
                        ...
Spain                    536.0
Belgium                  552.0
Unified Team             574.0
Turkey                   382.0
Netherlands             1454.0
Austria                 1138.0
New Zealand              406.0
Denmark                  670.0
West Germany             918.0
Czechoslovakia           654.0
Bulgaria                 822.0
South Korea             1218.0
Poland                  1040.0
Finland                 1790.0
Norway                  1970.0
Cuba                     840.0
Russia                  2084.0
Romania                 1144.0
Sweden                  2434.0
Germany                 3092.0
East Germany            2136.0
Japan                   1732.0
Australia               1846.0
Italy                   2666.0
Hungary                 1924.0
France                  3000.0
China                   2240.0
Great Britain           3148.0
Soviet Union            5052.0
United States          11368.0
Name: T_Gold, Length: 146, dtype: float64

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

In [70]:
census_df = pd.read_csv('census.csv')
census_df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
6,50,3,6,1,11,Alabama,Bullock County,10914,10915,10887,...,-30.953709,-5.180127,-1.130263,14.354290,-16.167247,-29.001673,-2.825524,1.507017,17.243790,-13.193961
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20944,...,-14.032727,-11.684234,-5.655413,1.085428,-6.529805,-13.936612,-11.586865,-5.557058,1.184103,-6.430868
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118437,...,-6.155670,-4.611706,-5.524649,-4.463211,-3.376322,-5.791579,-4.092677,-5.062836,-3.912834,-2.806406
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34098,...,-2.731639,3.849092,2.872721,-2.287222,1.349468,-1.821092,4.701181,3.781439,-1.290228,2.346901
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25976,...,6.339327,1.113180,5.488706,-0.076806,-3.239866,6.416167,1.420264,5.757384,0.230419,-2.931307
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43665,...,-1.372935,-2.653369,0.480044,0.456017,-2.253483,-0.823761,-2.447504,0.868651,0.957636,-1.752709
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13841,...,-15.455274,-0.737028,-8.766391,-1.274984,-5.291205,-15.528177,-0.737028,-8.766391,-1.274984,-5.291205
13,50,3,6,1,25,Alabama,Clarke County,25833,25840,25767,...,-6.194363,-17.667705,-0.318345,-8.686428,-5.613667,-6.077488,-17.509958,-0.159172,-8.486280,-5.411736
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13880,...,-10.744102,-13.345130,4.902871,5.702648,3.912450,-10.816697,-13.345130,4.977157,5.776708,3.986270
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14973,...,-3.673524,-5.151880,7.345821,3.654485,-3.123961,-3.673524,-5.151880,7.345821,3.654485,-3.123961
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50177,...,0.377640,7.675579,-13.146535,-3.602859,2.214774,2.166460,11.513368,-10.438741,-0.767822,5.350738
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54514,...,-0.073423,1.065051,1.762390,1.835688,-0.110260,0.513964,1.469035,2.276420,2.533249,0.588052
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13208,...,-4.861559,-7.504690,-6.107224,-14.645416,2.684140,-4.861559,-7.504690,-6.107224,-14.645416,2.684140
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-33.930581,-10.291443,-4.313831,-22.958017,-5.387581,-34.017138,-10.380162,-4.403703,-23.049483,-5.387581
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37796,...,6.696899,-4.612668,0.740271,3.697932,-0.316945,6.881460,-4.559952,0.793147,3.750759,-0.264121
21,50,3,6,1,41,Alabama,Crenshaw County,13906,13906,13853,...,1.729792,3.950156,-1.864936,3.084648,3.439504,2.666763,5.099293,-0.502098,4.734577,5.087600
22,50,3,6,1,43,Alabama,Cullman County,80406,80410,80473,...,-1.404233,-1.019628,4.071247,5.087142,7.915406,-1.031427,-0.634159,4.542916,5.593387,8.417777
23,50,3,6,1,45,Alabama,Dale County,50251,50251,50358,...,-10.749798,-5.277150,-15.236079,-11.979785,-5.107706,-9.575283,-0.776637,-12.640155,-9.503292,-1.998668
24,50,3,6,1,47,Alabama,Dallas County,43820,43820,43803,...,-15.635599,-11.308243,-16.745678,-9.344789,-14.687232,-15.727573,-11.378047,-16.792849,-9.368689,-14.711389
25,50,3,6,1,49,Alabama,DeKalb County,71109,71115,71142,...,0.294677,-9.302391,-1.748807,0.267830,0.028141,1.375159,-8.656001,-1.029539,1.198187,0.956790
26,50,3,6,1,51,Alabama,Elmore County,79303,79296,79465,...,3.235576,0.822717,1.760531,-1.507057,2.067820,3.674511,1.558176,2.306047,-0.951175,2.757093
27,50,3,6,1,53,Alabama,Escambia County,38319,38319,38309,...,-3.449988,-3.855889,-4.822706,-1.189831,1.190902,-3.397716,-3.803428,-4.769999,-1.136950,1.243830
28,50,3,6,1,55,Alabama,Etowah County,104430,104427,104442,...,-1.015919,2.062637,-1.931884,-1.726932,-2.082234,-0.632554,2.446383,-1.518596,-1.234901,-1.588308
29,50,3,6,1,57,Alabama,Fayette County,17241,17241,17231,...,-5.015601,-0.646640,-3.725937,0.296745,-2.797536,-5.132243,-0.705426,-3.785079,0.237396,-2.857058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131885,131967,...,-0.794876,0.785279,-2.215465,1.601149,-0.434498,-0.431504,1.162817,-1.763330,2.104796,0.059931
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389938,390076,...,-0.765799,2.128860,0.038132,0.760109,-0.719858,0.102448,3.180527,1.189727,2.077633,0.593567
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52422,...,3.111756,-2.241873,6.292687,-0.441031,-0.480617,3.359933,-2.011937,6.561277,-0.134227,-0.173022
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24506,...,4.930022,-2.404973,-4.097017,-4.906711,-4.397793,5.174486,-2.160399,-3.810226,-4.535615,-4.024395
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167059,...,0.316712,2.889873,0.833819,-2.406192,-4.557985,0.842573,3.502335,1.531624,-1.545153,-3.685304
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74807,...,-4.081523,-5.019090,-6.901200,-5.596471,-3.958322,-3.733590,-4.562809,-6.442917,-5.040889,-3.414223
3169,40,4,8,56,0,Wyoming,Wyoming,563626,563767,564516,...,-0.381530,9.636214,4.487115,-4.788275,-3.221091,0.289680,10.694870,5.440390,-3.727831,-2.091573
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,3.708956,2.637812,-3.544634,-3.334877,-9.911169,6.736119,6.433032,0.719587,1.429233,-5.166460
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11672,...,4.868258,2.804930,16.815908,-8.026420,5.095861,4.868258,3.144921,17.236306,-7.608378,5.513554
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46244,...,-2.843479,15.601020,-5.895711,-8.550911,10.916963,-2.649606,15.558684,-5.916543,-8.509402,10.978525
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,-7.581980,-13.081441,3.178134,-2.970641,-23.300971,-7.392431,-12.636926,3.623073,-2.338590,-22.600668
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13826,...,-12.847499,15.493820,19.035533,-20.550587,-0.070403,-12.774915,16.502720,20.093063,-19.358233,1.126443
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7114,...,-1.544618,-4.202564,1.397819,6.378258,18.629317,-0.982939,-3.642222,2.096729,7.071547,19.309219
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,2.747083,7.782673,-4.990688,-12.331633,-13.673610,3.093562,8.027411,-4.747240,-12.013555,-13.352750
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13408,...,14.293649,3.961413,-8.079028,-7.017803,-11.899450,14.886132,4.841727,-6.903896,-5.761986,-10.635133
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,3.322604,6.208609,3.095336,-6.017222,-5.454164,5.191569,6.001656,2.888981,-6.224712,-5.663940
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,4.995063,-4.058912,-0.812583,-10.715742,0.933652,5.227392,-4.058912,-0.812583,-10.715742,0.933652
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92271,...,-1.200428,15.547274,4.787847,-1.226133,0.278940,-0.973320,17.914554,6.003143,-0.207819,1.673640
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18091,...,-9.802564,-11.566801,13.564556,6.125989,1.555544,-9.691801,-11.566801,13.619696,6.234414,1.662823
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75472,...,7.189319,23.066162,24.322042,-0.958472,-0.061057,7.689674,23.749508,25.085233,-0.110593,0.793743
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,-0.401849,0.806452,29.066295,-12.603387,7.492114,-0.401849,0.806452,29.066295,-12.603387,7.492114
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28259,...,4.582951,8.057765,7.641997,-9.252437,-2.878980,6.486639,11.127389,10.877797,-5.585731,0.856839
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8678,...,4.373094,5.392073,2.634593,6.055759,4.662270,4.373094,4.933173,2.176403,5.598720,4.207414
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,0.958559,8.425487,4.546373,3.678069,-3.298406,2.122524,9.342778,5.523001,4.781489,-2.198937
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10244,...,-23.741784,15.272374,-40.870074,-16.596273,-22.870900,-21.092907,16.828794,-39.211861,-14.409938,-20.664059
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [71]:
df1=census_df.set_index(['STNAME','CTYNAME'])
df1

                              SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME    CTYNAME
Alabama   Alabama                 40       3         6      1       0
          Autauga County          50       3         6      1       1
          Baldwin County          50       3         6      1       3
          Barbour County          50       3         6      1       5
          Bibb County             50       3         6      1       7
          Blount County           50       3         6      1       9
          Bullock County          50       3         6      1      11
          Butler County           50       3         6      1      13
          Calhoun County          50       3         6      1      15
          Chambers County         50       3         6      1      17
          Cherokee County         50       3         6      1      19
          Chilton County          50       3         6      1      21
          Choctaw County          50       3         6      1      23
          Clarke County           50       3         6      1      25
          Clay County             50       3         6      1      27
          Cleburne County         50       3         6      1      29
          Coffee County           50       3         6      1      31
          Colbert County          50       3         6      1      33
          Conecuh County          50       3         6      1      35
          Coosa County            50       3         6      1      37
          Covington County        50       3         6      1      39
          Crenshaw County         50       3         6      1      41
          Cullman County          50       3         6      1      43
          Dale County             50       3         6      1      45
          Dallas County           50       3         6      1      47
          DeKalb County           50       3         6      1      49
          Elmore County           50       3         6      1      51
          Escambia County         50       3         6      1      53
          Etowah County           50       3         6      1      55
          Fayette County          50       3         6      1      57
...                              ...     ...       ...    ...     ...
Wisconsin Washington County       50       2         3     55     131
          Waukesha County         50       2         3     55     133
          Waupaca County          50       2         3     55     135
          Waushara County         50       2         3     55     137
          Winnebago County        50       2         3     55     139
          Wood County             50       2         3     55     141
Wyoming   Wyoming                 40       4         8     56       0
          Albany County           50       4         8     56       1
          Big Horn County         50       4         8     56       3
          Campbell County         50       4         8     56       5
          Carbon County           50       4         8     56       7
          Converse County         50       4         8     56       9
          Crook County            50       4         8     56      11
          Fremont County          50       4         8     56      13
          Goshen County           50       4         8     56      15
          Hot Springs County      50       4         8     56      17
          Johnson County          50       4         8     56      19
          Laramie County          50       4         8     56      21
          Lincoln County          50       4         8     56      23
          Natrona County          50       4         8     56      25
          Niobrara County         50       4         8     56      27
          Park County             50       4         8     56      29
          Platte County           50       4         8     56      31
          Sheridan County         50       4         8     56      33
          Sublette County         50       4         8     56      35
          Sweetwater County       50       4         8     56      37
          Teton County            50       4         8     56      39
          Uinta County            50       4         8     56      41
          Washakie County         50       4         8     56      43
          Weston County           50       4         8     56      45

                              CENSUS2010POP  ESTIMATESBASE2010  \
STNAME    CTYNAME
Alabama   Alabama                   4779736            4780127
          Autauga County              54571              54571
          Baldwin County             182265             182265
          Barbour County              27457              27457
          Bibb County                 22915              22919
          Blount County               57322              57322
          Bullock County              10914              10915
          Butler County               20947              20946
          Calhoun County             118572             118586
          Chambers County             34215              34170
          Cherokee County             25989              25986
          Chilton County              43643              43631
          Choctaw County              13859              13858
          Clarke County               25833              25840
          Clay County                 13932              13932
          Cleburne County             14972              14972
          Coffee County               49948              49948
          Colbert County              54428              54428
          Conecuh County              13228              13228
          Coosa County                11539              11758
          Covington County            37765              37765
          Crenshaw County             13906              13906
          Cullman County              80406              80410
          Dale County                 50251              50251
          Dallas County               43820              43820
          DeKalb County               71109              71115
          Elmore County               79303              79296
          Escambia County             38319              38319
          Etowah County              104430             104427
          Fayette County              17241              17241
...                                     ...                ...
Wisconsin Washington County          131887             131885
          Waukesha County            389891             389938
          Waupaca County              52410              52410
          Waushara County             24496              24496
          Winnebago County           166994             166994
          Wood County                 74749              74749
Wyoming   Wyoming                    563626             563767
          Albany County               36299              36299
          Big Horn County             11668              11668
          Campbell County             46133              46133
          Carbon County               15885              15885
          Converse County             13833              13833
          Crook County                 7083               7083
          Fremont County              40123              40123
          Goshen County               13249              13247
          Hot Springs County           4812               4812
          Johnson County               8569               8569
          Laramie County              91738              91881
          Lincoln County              18106              18106
          Natrona County              75450              75450
          Niobrara County              2484               2484
          Park County                 28205              28205
          Platte County                8667               8667
          Sheridan County             29116              29116
          Sublette County             10247              10247
          Sweetwater County           43806              43806
          Teton County                21294              21294
          Uinta County                21118              21118
          Washakie County              8533               8533
          Weston County                7208               7208

                              POPESTIMATE2010  POPESTIMATE2011  \
STNAME    CTYNAME
Alabama   Alabama                     4785161          4801108
          Autauga County                54660            55253
          Baldwin County               183193           186659
          Barbour County                27341            27226
          Bibb County                   22861            22733
          Blount County                 57373            57711
          Bullock County                10887            10629
          Butler County                 20944            20673
          Calhoun County               118437           117768
          Chambers County               34098            33993
          Cherokee County               25976            26080
          Chilton County                43665            43739
          Choctaw County                13841            13593
          Clarke County                 25767            25570
          Clay County                   13880            13670
          Cleburne County               14973            14971
          Coffee County                 50177            50448
          Colbert County                54514            54443
          Conecuh County                13208            13121
          Coosa County                  11758            11348
          Covington County              37796            38060
          Crenshaw County               13853            13896
          Cullman County                80473            80469
          Dale County                   50358            50109
          Dallas County                 43803            43178
          DeKalb County                 71142            71387
          Elmore County                 79465            80012
          Escambia County               38309            38213
          Etowah County                104442           104236
          Fayette County                17231            17062
...                                       ...              ...
Wisconsin Washington County            131967           132225
          Waukesha County              390076           390808
          Waupaca County                52422            52342
          Waushara County               24506            24581
          Winnebago County             167059           167630
          Wood County                   74807            74647
Wyoming   Wyoming                      564516           567768
          Albany County                 36428            36908
          Big Horn County               11672            11745
          Campbell County               46244            46600
          Carbon County                 15837            15817
          Converse County               13826            13728
          Crook County                   7114             7129
          Fremont County                40222            40591
          Goshen County                 13408            13597
          Hot Springs County             4813             4818
          Johnson County                 8581             8636
          Laramie County                92271            92663
          Lincoln County                18091            18022
          Natrona County                75472            76420
          Niobrara County                2492             2485
          Park County                   28259            28473
          Platte County                  8678             8701
          Sheridan County               29146            29275
          Sublette County               10244            10142
          Sweetwater County             43593            44041
          Teton County                  21297            21482
          Uinta County                  21102            20912
          Washakie County                8545             8469
          Weston County                  7181             7114

                              POPESTIMATE2012     ...       RDOMESTICMIG2011  \
STNAME    CTYNAME                                 ...
Alabama   Alabama                     4816089     ...               0.002295
          Autauga County                55175     ...               7.242091
          Baldwin County               190396     ...              14.832960
          Barbour County                27159     ...              -4.728132
          Bibb County                   22642     ...              -5.527043
          Blount County                 57776     ...               1.807375
          Bullock County                10606     ...             -30.953709
          Butler County                 20408     ...             -14.032727
          Calhoun County               117286     ...              -6.155670
          Chambers County               34075     ...              -2.731639
          Cherokee County               26023     ...               6.339327
          Chilton County                43697     ...              -1.372935
          Choctaw County                13543     ...             -15.455274
          Clarke County                 25144     ...              -6.194363
          Clay County                   13456     ...             -10.744102
          Cleburne County               14921     ...              -3.673524
          Coffee County                 51173     ...               0.377640
          Colbert County                54472     ...              -0.073423
          Conecuh County                12996     ...              -4.861559
          Coosa County                  11195     ...             -33.930581
          Covington County              37818     ...               6.696899
          Crenshaw County               13951     ...               1.729792
          Cullman County                80374     ...              -1.404233
          Dale County                   50324     ...             -10.749798
          Dallas County                 42777     ...             -15.635599
          DeKalb County                 70942     ...               0.294677
          Elmore County                 80432     ...               3.235576
          Escambia County               38034     ...              -3.449988
          Etowah County                104235     ...              -1.015919
          Fayette County                16960     ...              -5.015601
...                                       ...     ...                    ...
Wisconsin Washington County            132649     ...              -0.794876
          Waukesha County              392710     ...              -0.765799
          Waupaca County                52035     ...               3.111756
          Waushara County               24484     ...               4.930022
          Winnebago County             168717     ...               0.316712
          Wood County                   74384     ...              -4.081523
Wyoming   Wyoming                      577080     ...              -0.381530
          Albany County                 37396     ...               3.708956
          Big Horn County               11785     ...               4.868258
          Campbell County               47881     ...              -2.843479
          Carbon County                 15678     ...              -7.581980
          Converse County               14025     ...             -12.847499
          Crook County                   7148     ...              -1.544618
          Fremont County                41129     ...               2.747083
          Goshen County                 13666     ...              14.293649
          Hot Springs County             4846     ...               3.322604
          Johnson County                 8610     ...               4.995063
          Laramie County                94894     ...              -1.200428
          Lincoln County                17943     ...              -9.802564
          Natrona County                78699     ...               7.189319
          Niobrara County                2475     ...              -0.401849
          Park County                   28863     ...               4.582951
          Platte County                  8732     ...               4.373094
          Sheridan County               29594     ...               0.958559
          Sublette County               10418     ...             -23.741784
          Sweetwater County             45104     ...               1.072643
          Teton County                  21697     ...              -1.589565
          Uinta County                  20989     ...             -17.755986
          Washakie County                8443     ...             -11.637475
          Weston County                  7065     ...             -11.752361

                              RDOMESTICMIG2012  RDOMESTICMIG2013  \
STNAME    CTYNAME
Alabama   Alabama                    -0.193196          0.381066
          Autauga County             -2.915927         -3.012349
          Baldwin County             17.647293         21.845705
          Barbour County             -2.500690         -7.056824
          Bibb County                -5.068871         -6.201001
          Blount County              -1.177622         -1.748766
          Bullock County             -5.180127         -1.130263
          Butler County             -11.684234         -5.655413
          Calhoun County             -4.611706         -5.524649
          Chambers County             3.849092          2.872721
          Cherokee County             1.113180          5.488706
          Chilton County             -2.653369          0.480044
          Choctaw County             -0.737028         -8.766391
          Clarke County             -17.667705         -0.318345
          Clay County               -13.345130          4.902871
          Cleburne County            -5.151880          7.345821
          Coffee County               7.675579        -13.146535
          Colbert County              1.065051          1.762390
          Conecuh County             -7.504690         -6.107224
          Coosa County              -10.291443         -4.313831
          Covington County           -4.612668          0.740271
          Crenshaw County             3.950156         -1.864936
          Cullman County             -1.019628          4.071247
          Dale County                -5.277150        -15.236079
          Dallas County             -11.308243        -16.745678
          DeKalb County              -9.302391         -1.748807
          Elmore County               0.822717          1.760531
          Escambia County            -3.855889         -4.822706
          Etowah County               2.062637         -1.931884
          Fayette County             -0.646640         -3.725937
...                                        ...               ...
Wisconsin Washington County           0.785279         -2.215465
          Waukesha County             2.128860          0.038132
          Waupaca County             -2.241873          6.292687
          Waushara County            -2.404973         -4.097017
          Winnebago County            2.889873          0.833819
          Wood County                -5.019090         -6.901200
Wyoming   Wyoming                     9.636214          4.487115
          Albany County               2.637812         -3.544634
          Big Horn County             2.804930         16.815908
          Campbell County            15.601020         -5.895711
          Carbon County             -13.081441          3.178134
          Converse County            15.493820         19.035533
          Crook County               -4.202564          1.397819

In [73]:
df1=census_df.set_index(['STNAME'])
u=df1.index.unique()

In [74]:
len(u)

51

In [75]:
s=[]
for i in u :
    s.append(len(df1.loc[i]))
print(s)

[68, 30, 16, 76, 59, 65, 9, 4, 2, 68, 160, 6, 45, 103, 93, 100, 106, 121, 65, 17, 25, 15, 84, 88, 83, 116, 57, 94, 18, 11, 22, 34, 63, 101, 54, 89, 78, 37, 68, 6, 47, 67, 96, 255, 30, 15, 134, 40, 56, 73, 24]

In [82]:
s=[len(df1.loc[i]) for i in u]
print(s)

[68, 30, 16, 76, 59, 65, 9, 4, 2, 68, 160, 6, 45, 103, 93, 100, 106, 121, 65, 17, 25, 15, 84, 88, 83, 116, 57, 94, 18, 11, 22, 34, 63, 101, 54, 89, 78, 37, 68, 6, 47, 67, 96, 255, 30, 15, 134, 40, 56, 73, 24]

In [76]:
S2=pd.Series(s, index=u)
S2.sort_values()

STNAME
District of Columbia      2
Delaware                  4
Rhode Island              6
Hawaii                    6
Connecticut               9
New Hampshire            11
Massachusetts            15
Vermont                  15
Arizona                  16
Maine                    17
Nevada                   18
New Jersey               22
Wyoming                  24
Maryland                 25
Utah                     30
Alaska                   30
New Mexico               34
Oregon                   37
Washington               40
Idaho                    45
South Carolina           47
North Dakota             54
West Virginia            56
Montana                  57
California               59
New York                 63
Louisiana                65
Colorado                 65
South Dakota             67
Pennsylvania             68
Alabama                  68
Florida                  68
Wisconsin                73
Arkansas                 76
Oklahoma                 78
Mississippi              83
Michigan                 84
Minnesota                88
Ohio                     89
Indiana                  93
Nebraska                 94
Tennessee                96
Iowa                    100
North Carolina          101
Illinois                103
Kansas                  106
Missouri                116
Kentucky                121
Virginia                134
Georgia                 160
Texas                   255
dtype: int64

In [77]:
print(S2.iloc[-1])

24

In [79]:
S2.argmax()

'Texas'

In [85]:
#Done
def answer_five(df1=df1):

    census_df = pd.read_csv('census.csv')
#     df1=census_df.set_index(['STNAME','CTYNAME'])
    df1=census_df.set_index(['STNAME'])
    u=df1.index.unique()
    s=[len(df1.loc[i]) for i in u]
    S2=pd.Series(s, index=u)
    return S2.argmax()

answer_five()

'Texas'

In [86]:
def answer_five(df1=df1):
    df1=census_df.set_index(['STNAME','CTYNAME'])
    s=[]
    for i in u :
        s.append(len(df1.loc[i]))
#     print(s)
    S2=pd.Series(s, index=u)
    S2=S2.sort_values()
    
    return S2.iloc[-1]

answer_five()

255

### Question 6
**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [109]:
census_df = pd.read_csv('census.csv')
df6=census_df

In [246]:
u_State=set(df6.index)
u_county=set(df6['CTYNAME'])

In [247]:
df6.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
STNAME,,,,,,,,,,,,,,,,,,,,,
Alabama,40,3,6,1,0,Alabama,4779736,4780127,4785161,4801108,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
Alabama,50,3,6,1,1,Autauga County,54571,54571,54660,55253,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
Alabama,50,3,6,1,3,Baldwin County,182265,182265,183193,186659,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
Alabama,50,3,6,1,5,Barbour County,27457,27457,27341,27226,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
Alabama,50,3,6,1,7,Bibb County,22915,22919,22861,22733,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [305]:
CENSUS_List.iloc[4]

22915

In [306]:
df6=census_df.set_index(['STNAME','CTYNAME'])
# df3=df3.set_index(['STNAME','CTYNAME'])
s6=df6['CENSUS2010POP']
s6

STNAME     CTYNAME
Alabama    Alabama               4779736
           Autauga County          54571
           Baldwin County         182265
           Barbour County          27457
           Bibb County             22915
           Blount County           57322
           Bullock County          10914
           Butler County           20947
           Calhoun County         118572
           Chambers County         34215
           Cherokee County         25989
           Chilton County          43643
           Choctaw County          13859
           Clarke County           25833
           Clay County             13932
           Cleburne County         14972
           Coffee County           49948
           Colbert County          54428
           Conecuh County          13228
           Coosa County            11539
           Covington County        37765
           Crenshaw County         13906
           Cullman County          80406
           Dale County             50251
           Dallas County           43820
           DeKalb County           71109
           Elmore County           79303
           Escambia County         38319
           Etowah County          104430
           Fayette County          17241
                                  ...
Wisconsin  Washington County      131887
           Waukesha County        389891
           Waupaca County          52410
           Waushara County         24496
           Winnebago County       166994
           Wood County             74749
Wyoming    Wyoming                563626
           Albany County           36299
           Big Horn County         11668
           Campbell County         46133
           Carbon County           15885
           Converse County         13833
           Crook County             7083
           Fremont County          40123
           Goshen County           13249
           Hot Springs County       4812
           Johnson County           8569
           Laramie County          91738
           Lincoln County          18106
           Natrona County          75450
           Niobrara County          2484
           Park County             28205
           Platte County            8667
           Sheridan County         29116
           Sublette County         10247
           Sweetwater County       43806
           Teton County            21294
           Uinta County            21118
           Washakie County          8533
           Weston County            7208
Name: CENSUS2010POP, Length: 3193, dtype: int64

In [320]:
s6.loc[['Alabama']]

STNAME   CTYNAME
Alabama  Alabama              4779736
         Autauga County         54571
         Baldwin County        182265
         Barbour County         27457
         Bibb County            22915
         Blount County          57322
         Bullock County         10914
         Butler County          20947
         Calhoun County        118572
         Chambers County        34215
         Cherokee County        25989
         Chilton County         43643
         Choctaw County         13859
         Clarke County          25833
         Clay County            13932
         Cleburne County        14972
         Coffee County          49948
         Colbert County         54428
         Conecuh County         13228
         Coosa County           11539
         Covington County       37765
         Crenshaw County        13906
         Cullman County         80406
         Dale County            50251
         Dallas County          43820
         DeKalb County          71109
         Elmore County          79303
         Escambia County        38319
         Etowah County         104430
         Fayette County         17241
                               ...
         Lamar County           14564
         Lauderdale County      92709
         Lawrence County        34339
         Lee County            140247
         Limestone County       82782
         Lowndes County         11299
         Macon County           21452
         Madison County        334811
         Marengo County         21027
         Marion County          30776
         Marshall County        93019
         Mobile County         412992
         Monroe County          23068
         Montgomery County     229363
         Morgan County         119490
         Perry County           10591
         Pickens County         19746
         Pike County            32899
         Randolph County        22913
         Russell County         52947
         St. Clair County       83593
         Shelby County         195085
         Sumter County          13763
         Talladega County       82291
         Tallapoosa County      41616
         Tuscaloosa County     194656
         Walker County          67023
         Washington County      17581
         Wilcox County          11670
         Winston County         24484
Name: CENSUS2010POP, Length: 68, dtype: int64

In [321]:
l=[]                           #list l for storing sum of 3 largest(populus county) value of each state
for s in u_State:              # iterating over all the states 
#     going  in by multilevel index ['Alabama','Alabama County'] this will list each county index
    
    k=s6.loc[[s, s +' County']].nlargest(3).sum()  # k is the sum of 3 largst county for each state
    l.append(k)                                    # storing value of each k in  list l
    
#     print(k)
    
    count+=1
print(type(k))
print(l)

18942231
24113524
8849266
5851194
3399687
4310104
7122794
15451733
9451014
2150226
5073387
1203446
2148870
12906586
2930976
1246686
11413555
1099638
5096118
3520005
3895662
7608749
5073227
5461093
13980040
11356104
903677
2012414
6251617
50167874
7662039
10506868
5406095
23045811
11189397
5384940
2628858
1084596
1845392
843928
3688221
1807166
730814
6964990
5376266
7900430
31606159
7883200
9520744
2498587
1633558
<class 'int'>
[18942231, 24113524, 8849266, 5851194, 3399687, 4310104, 7122794, 15451733, 9451014, 2150226, 5073387, 1203446, 2148870, 12906586, 2930976, 1246686, 11413555, 1099638, 5096118, 3520005, 3895662, 7608749, 5073227, 5461093, 13980040, 11356104, 903677, 2012414, 6251617, 50167874, 7662039, 10506868, 5406095, 23045811, 11189397, 5384940, 2628858, 1084596, 1845392, 843928, 3688221, 1807166, 730814, 6964990, 5376266, 7900430, 31606159, 7883200, 9520744, 2498587, 1633558]

In [291]:
pdS=pd.Series(l, index=u_State)    # Making a new series  from l (list of  ) with its indexes from u_state
pdS.nlargest(3)  # again applying  nlargest on this series

California    50167874
Texas         31606159
New York      24113524
dtype: int64

In [325]:
dd=pdS.nlargest(3)
print(dd.index)

Index(['California', 'Texas', 'New York'], dtype='object')

In [322]:
# iteratining over each  state we get 3 largest  population and store  it as a series in k

for s in u_State:
    k=s3.loc[[s, s +' County']].nlargest(3)
    print(k)

STNAME    CTYNAME
Illinois  Illinois         12830632
          Cook County       5194675
          DuPage County      916924
Name: C2010POP, dtype: int64
STNAME    CTYNAME
New York  New York         19378102
          Kings County      2504700
          Queens County     2230722
Name: C2010POP, dtype: int64
STNAME         CTYNAME
Massachusetts  Massachusetts       6547629
               Middlesex County    1503085
               Worcester County     798552
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Alabama  Alabama             4779736
         Jefferson County     658466
         Mobile County        412992
Name: C2010POP, dtype: int64
STNAME       CTYNAME
Mississippi  Mississippi        2967297
             Hinds County        245285
             Harrison County     187105
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Utah    Utah                2763885
        Salt Lake County    1029655
        Utah County          516564
Name: C2010POP, dtype: int64
STNAME     CTYNAME
Wisconsin  Wisconsin           5686986
           Milwaukee County     947735
           Dane County          488073
Name: C2010POP, dtype: int64
STNAME        CTYNAME
Pennsylvania  Pennsylvania           12702379
              Philadelphia County     1526006
              Allegheny County        1223348
Name: C2010POP, dtype: int64
STNAME      CTYNAME
Washington  Washington       6724540
            King County      1931249
            Pierce County     795225
Name: C2010POP, dtype: int64
STNAME         CTYNAME
West Virginia  West Virginia      1852994
               Kanawha County      193063
               Berkeley County     104169
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Oklahoma  Oklahoma           3751351
          Oklahoma County     718633
          Tulsa County        603403
Name: C2010POP, dtype: int64
STNAME                CTYNAME
District of Columbia  District of Columbia    601723
                      District of Columbia    601723
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Idaho   Idaho            1567582
        Ada County        392365
        Canyon County     188923
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Michigan  Michigan          9883640
          Wayne County      1820584
          Oakland County    1202362
Name: C2010POP, dtype: int64
STNAME      CTYNAME
New Mexico  New Mexico           2059179
            Bernalillo County     662564
            DoÃ±a Ana County       209233
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Montana  Montana               989415
         Yellowstone County    147972
         Missoula County       109299
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Georgia  Georgia            9687653
         Fulton County       920581
         Gwinnett County     805321
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Alaska  Alaska                          710231
        Anchorage Municipality          291826
        Fairbanks North Star Borough     97581
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Oregon  Oregon               3831074
        Multnomah County      735334
        Washington County     529710
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Arkansas  Arkansas          2915918
          Pulaski County     382748
          Benton County      221339
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Kansas  Kansas             2853118
        Johnson County      544179
        Sedgwick County     498365
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Maryland  Maryland                  5773552
          Montgomery County          971777
          Prince George's County     863420
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Nevada  Nevada           2700551
        Clark County     1951269
        Washoe County     421407
Name: C2010POP, dtype: int64
STNAME          CTYNAME
South Carolina  South Carolina       4625364
                Greenville County     451225
                Richland County       384504
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Ohio    Ohio               11536504
        Cuyahoga County     1280122
        Franklin County     1163414
Name: C2010POP, dtype: int64
STNAME          CTYNAME
North Carolina  North Carolina        9535483
                Mecklenburg County     919628
                Wake County            900993
Name: C2010POP, dtype: int64
STNAME        CTYNAME
North Dakota  North Dakota       672591
              Cass County        149778
              Burleigh County     81308
Name: C2010POP, dtype: int64
STNAME         CTYNAME
New Hampshire  New Hampshire          1316470
               Hillsborough County     400721
               Rockingham County       295223
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Colorado  Colorado          5029196
          El Paso County     622263
          Denver County      600158
Name: C2010POP, dtype: int64
STNAME      CTYNAME
California  California            37253956
            Los Angeles County     9818605
            San Diego County       3095313
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Missouri  Missouri            5988927
          St. Louis County     998954
          Jackson County       674158
Name: C2010POP, dtype: int64
STNAME      CTYNAME
New Jersey  New Jersey          8791894
            Bergen County        905116
            Middlesex County     809858
Name: C2010POP, dtype: int64
STNAME     CTYNAME
Louisiana  Louisiana                  4533372
           East Baton Rouge Parish     440171
           Jefferson Parish            432552
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Florida  Florida              18801310
         Miami-Dade County     2496435
         Broward County        1748066
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Arizona  Arizona            6392017
         Maricopa County    3817117
         Pima County         980263
Name: C2010POP, dtype: int64
STNAME       CTYNAME
Connecticut  Connecticut         3574097
             Fairfield County     916829
             Hartford County      894014
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Nebraska  Nebraska            1826341
          Douglas County       517110
          Lancaster County     285407
Name: C2010POP, dtype: int64
STNAME        CTYNAME
South Dakota  South Dakota         814180
              Minnehaha County     169468
              Pennington County    100948
Name: C2010POP, dtype: int64
STNAME        CTYNAME
Rhode Island  Rhode Island         1052567
              Providence County     626667
              Kent County           166158
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Vermont  Vermont              625741
         Chittenden County    156545
         Rutland County        61642
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Iowa    Iowa           3046355
        Polk County     430640
        Linn County     211226
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Maine   Maine                1328361
        Cumberland County     281674
        York County           197131
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Wyoming  Wyoming           563626
         Laramie County     91738
         Natrona County     75450
Name: C2010POP, dtype: int64
STNAME     CTYNAME
Minnesota  Minnesota          5303925
           Hennepin County    1152425
           Ramsey County       508640
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Kentucky  Kentucky            4339367
          Jefferson County     741096
          Fayette County       295803
Name: C2010POP, dtype: int64
STNAME     CTYNAME
Tennessee  Tennessee          6346105
           Shelby County       927644
           Davidson County     626681
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Texas   Texas            25145561
        Harris County     4092459
        Dallas County     2368139
Name: C2010POP, dtype: int64
STNAME   CTYNAME
Indiana  Indiana          6483802
         Marion County     903393
         Lake County       496005
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Virginia  Virginia               8001024
          Fairfax County         1081726
          Virginia Beach city     437994
Name: C2010POP, dtype: int64
STNAME  CTYNAME
Hawaii  Hawaii             1360301
        Honolulu County     953207
        Hawaii County       185079
Name: C2010POP, dtype: int64
STNAME    CTYNAME
Delaware  Delaware             897934
          New Castle County    538479
          Sussex County        197145
Name: C2010POP, dtype: int64

In [266]:
type(k)
k

STNAME    CTYNAME
Delaware  Delaware             897934
          New Castle County    538479
          Sussex County        197145
Name: C2010POP, dtype: int64

In [259]:
s3.loc[['Washington', 'Washington County']].nlargest(3)

STNAME      CTYNAME
Washington  Washington       6724540
            King County      1931249
            Pierce County     795225
Name: C2010POP, dtype: int64

In [256]:
s3.index

MultiIndex(levels=[['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'], ['Abbeville County', 'Acadia Parish', 'Accomack County', 'Ada County', 'Adair County', 'Adams County', 'Addison County', 'Aiken County', 'Aitkin County', 'Alabama', 'Alachua County', 'Alamance County', 'Alameda County', 'Alamosa County', 'Alaska', 'Albany County', 'Albemarle County', 'Alcona County', 'Alcorn County', 'Aleutians East Borough', 'Aleutians West Census Area', 'Alexander County', 'Alexandria city', 'Alfalfa County', 'Alger County', 'Allamakee County', 'Allegan County', 'Allegany County', 'Alleghany County', 'Allegheny County', 'Allen County', 'Allen Parish', 'Allendale County', 'Alpena County', 'Alpine County', 'Amador County', 'Amelia County', 'Amherst County', 'Amite County', 'Anchorage Municipality', 'Anderson County', 'Andrew County', 'Andrews County', 'Androscoggin County', 'Angelina County', 'Anne Arundel County', 'Anoka County', 'Anson County', 'Antelope County', 'Antrim County', 'Apache County', 'Appanoose County', 'Appling County', 'Appomattox County', 'Aransas County', 'Arapahoe County', 'Archer County', 'Archuleta County', 'Arenac County', 'Arizona', 'Arkansas', 'Arkansas County', 'Arlington County', 'Armstrong County', 'Aroostook County', 'Arthur County', 'Ascension Parish', 'Ashe County', 'Ashland County', 'Ashley County', 'Ashtabula County', 'Asotin County', 'Assumption Parish', 'Atascosa County', 'Atchison County', 'Athens County', 'Atkinson County', 'Atlantic County', 'Atoka County', 'Attala County', 'Audrain County', 'Audubon County', 'Auglaize County', 'Augusta County', 'Aurora County', 'Austin County', 'Autauga County', 'Avery County', 'Avoyelles Parish', 'Baca County', 'Bacon County', 'Bailey County', 'Baker County', 'Baldwin County', 'Ballard County', 'Baltimore County', 'Baltimore city', 'Bamberg County', 'Bandera County', 'Banks County', 'Banner County', 'Bannock County', 'Baraga County', 'Barber County', 'Barbour County', 'Barnes County', 'Barnstable County', 'Barnwell County', 'Barren County', 'Barron County', 'Barrow County', 'Barry County', 'Bartholomew County', 'Barton County', 'Bartow County', 'Bastrop County', 'Bates County', 'Bath County', 'Baxter County', 'Bay County', 'Bayfield County', 'Baylor County', 'Beadle County', 'Bear Lake County', 'Beaufort County', 'Beauregard Parish', 'Beaver County', 'Beaverhead County', 'Becker County', 'Beckham County', 'Bedford County', 'Bee County', 'Belknap County', 'Bell County', 'Belmont County', 'Beltrami County', 'Ben Hill County', 'Benewah County', 'Bennett County', 'Bennington County', 'Benson County', 'Bent County', 'Benton County', 'Benzie County', 'Bergen County', 'Berkeley County', 'Berks County', 'Berkshire County', 'Bernalillo County', 'Berrien County', 'Bertie County', 'Bethel Census Area', 'Bexar County', 'Bibb County', 'Bienville Parish', 'Big Horn County', 'Big Stone County', 'Billings County', 'Bingham County', 'Black Hawk County', 'Blackford County', 'Bladen County', 'Blaine County', 'Blair County', 'Blanco County', 'Bland County', 'Bleckley County', 'Bledsoe County', 'Blount County', 'Blue Earth County', 'Boise County', 'Bolivar County', 'Bollinger County', 'Bon Homme County', 'Bond County', 'Bonner County', 'Bonneville County', 'Boone County', 'Borden County', 'Bosque County', 'Bossier Parish', 'Botetourt County', 'Bottineau County', 'Boulder County', 'Boundary County', 'Bourbon County', 'Bowie County', 'Bowman County', 'Box Butte County', 'Box Elder County', 'Boyd County', 'Boyle County', 'Bracken County', 'Bradford County', 'Bradley County', 'Branch County', 'Brantley County', 'Braxton County', 'Brazoria County', 'Brazos County', 'Breathitt County', 'Breckinridge County', 'Bremer County', 'Brevard County', 'Brewster County', 'Briscoe County', 'Bristol Bay Borough', 'Bristol County', 'Bristol city', 'Broadwater County', 'Bronx County', 'Brooke County', 'Brookings County', 'Brooks County', 'Broome County', 'Broomfield County', 'Broward County', 'Brown County', 'Brule County', 'Brunswick County', 'Bryan County', 'Buchanan County', 'Buckingham County', 'Bucks County', 'Buena Vista County', 'Buena Vista city', 'Buffalo County', 'Bullitt County', 'Bulloch County', 'Bullock County', 'Buncombe County', 'Bureau County', 'Burke County', 'Burleigh County', 'Burleson County', 'Burlington County', 'Burnet County', 'Burnett County', 'Burt County', 'Butler County', 'Butte County', 'Butts County', 'Cabarrus County', 'Cabell County', 'Cache County', 'Caddo County', 'Caddo Parish', 'Calaveras County', 'Calcasieu Parish', 'Caldwell County', 'Caldwell Parish', 'Caledonia County', 'Calhoun County', 'California', 'Callahan County', 'Callaway County', 'Calloway County', 'Calumet County', 'Calvert County', 'Camas County', 'Cambria County', 'Camden County', 'Cameron County', 'Cameron Parish', 'Camp County', 'Campbell County', 'Canadian County', 'Candler County', 'Cannon County', 'Canyon County', 'Cape Girardeau County', 'Cape May County', 'Carbon County', 'Caribou County', 'Carlisle County', 'Carlton County', 'Caroline County', 'Carroll County', 'Carson City', 'Carson County', 'Carter County', 'Carteret County', 'Carver County', 'Cascade County', 'Casey County', 'Cass County', 'Cassia County', 'Castro County', 'Caswell County', 'Catahoula Parish', 'Catawba County', 'Catoosa County', 'Catron County', 'Cattaraugus County', 'Cavalier County', 'Cayuga County', 'Cecil County', 'Cedar County', 'Centre County', 'Cerro Gordo County', 'Chaffee County', 'Chambers County', 'Champaign County', 'Chariton County', 'Charles City County', 'Charles County', 'Charles Mix County', 'Charleston County', 'Charlevoix County', 'Charlotte County', 'Charlottesville city', 'Charlton County', 'Chase County', 'Chatham County', 'Chattahoochee County', 'Chattooga County', 'Chautauqua County', 'Chaves County', 'Cheatham County', 'Cheboygan County', 'Chelan County', 'Chemung County', 'Chenango County', 'Cherokee County', 'Cherry County', 'Chesapeake city', 'Cheshire County', 'Chester County', 'Chesterfield County', 'Cheyenne County', 'Chickasaw County', 'Chicot County', 'Childress County', 'Chilton County', 'Chippewa County', 'Chisago County', 'Chittenden County', 'Choctaw County', 'Chouteau County', 'Chowan County', 'Christian County', 'Churchill County', 'Cibola County', 'Cimarron County', 'Citrus County', 'Clackamas County', 'Claiborne County', 'Claiborne Parish', 'Clallam County', 'Clare County', 'Clarendon County', 'Clarion County', 'Clark County', 'Clarke County', 'Clatsop County', 'Clay County', 'Clayton County', 'Clear Creek County', 'Clearfield County', 'Clearwater County', 'Cleburne County', 'Clermont County', 'Cleveland County', 'Clinch County', 'Clinton County', 'Cloud County', 'Coahoma County', 'Coal County', 'Cobb County', 'Cochise County', 'Cochran County', 'Cocke County', 'Coconino County', 'Codington County', 'Coffee County', 'Coffey County', 'Coke County', 'Colbert County', 'Cole County', 'Coleman County', 'Coles County', 'Colfax County', 'Colleton County', 'Collier County', 'Collin County', 'Collingsworth County', 'Colonial Heights city', 'Colorado', 'Colorado County', 'Colquitt County', 'Columbia County', 'Columbiana County', 'Columbus County', 'Colusa County', 'Comal County', 'Comanche County', 'Concho County', 'Concordia Parish', 'Conecuh County', 'Conejos County', 'Connecticut', 'Contra Costa County', 'Converse County', 'Conway County', 'Cook County', 'Cooke County', 'Cooper County', 'Coos County', 'Coosa County', 'Copiah County', 'Corson County', 'Cortland County', 'Coryell County', 'Coshocton County', 'Costilla County', 'Cottle County', 'Cotton County', 'Cottonwood County', 'Covington County', 'Covington city', 'Coweta County', 'Cowley County', 'Cowlitz County', 'Craig County', 'Craighead County', 'Crane County', 'Craven County', 'Crawford County', 'Creek County', 'Crenshaw County', 'Crisp County', 'Crittenden County', 'Crockett County', 'Crook County', 'Crosby County', 'Cross County', 'Crow Wing County', 'Crowley County', 'Culberson County', 'Cullman County', 'Culpeper County', 'Cumberland County', 'Cuming County', 'Currituck County', 'Curry County', 'Custer County', 'Cuyahoga County', 'Dade County', 'Daggett County', 'Dakota County', 'Dale County', 'Dallam County', 'Dallas County', 'Dane County', 'Daniels County', 'Danville city', 'Dare County', 'Darke County', 'Darlington County', 'Dauphin County', 'Davidson County', 'Davie County', 'Daviess County', 'Davis County', 'Davison County', 'Dawes County', 'Dawson County', 'Day County', 'De Baca County', 'De Soto Parish', 'De Witt County', 'DeKalb County', 'DeSoto County', 'DeWitt County', 'Deaf Smith County', 'Dearborn County', 'Decatur County', 'Deer Lodge County', 'Defiance County', 'Del Norte County', 'Delaware', 'Delaware County', 'Delta County', 'Denali Borough', 'Dent County', 'Denton County', 'Denver County', 'Des Moines County', 'Deschutes County', 'Desha County', 'Deuel County', 'Dewey County', 'Dickens County', 'Dickenson County', 'Dickey County', 'Dickinson County', 'Dickson County', 'Dillingham Census Area', 'Dillon County', 'Dimmit County', 'Dinwiddie County', 'District of Columbia', 'Divide County', 'Dixie County', 'Dixon County', 'Doddridge County', 'Dodge County', 'Dolores County', 'Doniphan County', 'Donley County', 'Dooly County', 'Door County', 'Dorchester County', 'Dougherty County', 'Douglas County', 'DoÃ±a Ana County', 'Drew County', 'DuPage County', 'Dubois County', 'Dubuque County', 'Duchesne County', 'Dukes County', 'Dundy County', 'Dunklin County', 'Dunn County', 'Duplin County', 'Durham County', 'Dutchess County', 'Duval County', 'Dyer County', 'Eagle County', 'Early County', 'East Baton Rouge Parish', 'East Carroll Parish', 'East Feliciana Parish', 'Eastland County', 'Eaton County', 'Eau Claire County', 'Echols County', 'Ector County', 'Eddy County', 'Edgar County', 'Edgecombe County', 'Edgefield County', 'Edmonson County', 'Edmunds County', 'Edwards County', 'Effingham County', 'El Dorado County', 'El Paso County', 'Elbert County', 'Elk County', 'Elkhart County', 'Elko County', 'Elliott County', 'Ellis County', 'Ellsworth County', 'Elmore County', 'Emanuel County', 'Emery County', 'Emmet County', 'Emmons County', 'Emporia city', 'Erath County', 'Erie County', 'Escambia County', 'Esmeralda County', 'Essex County', 'Estill County', 'Etowah County', 'Eureka County', 'Evangeline Parish', 'Evans County', 'Fairbanks North Star Borough', 'Fairfax County', 'Fairfax city', 'Fairfield County', 'Fall River County', 'Fallon County', 'Falls Church city', 'Falls County', 'Fannin County', 'Faribault County', 'Faulk County', 'Faulkner County', 'Fauquier County', 'Fayette County', 'Fentress County', 'Fergus County', 'Ferry County', 'Fillmore County', 'Finney County', 'Fisher County', 'Flagler County', 'Flathead County', 'Fleming County', 'Florence County', 'Florida', 'Floyd County', 'Fluvanna County', 'Foard County', 'Fond du Lac County', 'Ford County', 'Forest County', 'Forrest County', 'Forsyth County', 'Fort Bend County', 'Foster County', 'Fountain County', 'Franklin County', 'Franklin Parish', 'Franklin city', 'Frederick County', 'Fredericksburg city', 'Freeborn County', 'Freestone County', 'Fremont County', 'Fresno County', 'Frio County', 'Frontier County', 'Fulton County', 'Furnas County', 'Gadsden County', 'Gage County', 'Gaines County', 'Galax city', 'Gallatin County', 'Gallia County', 'Galveston County', 'Garden County', 'Garfield County', 'Garland County', 'Garrard County', 'Garrett County', 'Garvin County', 'Garza County', 'Gasconade County', 'Gaston County', 'Gates County', 'Geary County', 'Geauga County', 'Gem County', 'Genesee County', 'Geneva County', 'Gentry County', 'George County', 'Georgetown County', 'Georgia', 'Gibson County', 'Gila County', 'Gilchrist County', 'Giles County', 'Gillespie County', 'Gilliam County', 'Gilmer County', 'Gilpin County', 'Glacier County', 'Glades County', 'Gladwin County', 'Glascock County', 'Glasscock County', 'Glenn County', 'Gloucester County', 'Glynn County', 'Gogebic County', 'Golden Valley County', 'Goliad County', 'Gonzales County', 'Goochland County', 'Goodhue County', 'Gooding County', 'Gordon County', 'Goshen County', 'Gosper County', 'Gove County', 'Grady County', 'Grafton County', 'Graham County', 'Grainger County', 'Grand County', 'Grand Forks County', 'Grand Isle County', 'Grand Traverse County', 'Granite County', 'Grant County', 'Grant Parish', 'Granville County', 'Gratiot County', 'Graves County', 'Gray County', 'Grays Harbor County', 'Grayson County', 'Greeley County', 'Green County', 'Green Lake County', 'Greenbrier County', 'Greene County', 'Greenlee County', 'Greensville County', 'Greenup County', 'Greenville County', 'Greenwood County', 'Greer County', 'Gregg County', 'Gregory County', 'Grenada County', 'Griggs County', 'Grimes County', 'Grundy County', 'Guadalupe County', 'Guernsey County', 'Guilford County', 'Gulf County', 'Gunnison County', 'Guthrie County', 'Gwinnett County', 'Haakon County', 'Habersham County', 'Haines Borough', 'Hale County', 'Halifax County', 'Hall County', 'Hamblen County', 'Hamilton County', 'Hamlin County', 'Hampden County', 'Hampshire County', 'Hampton County', 'Hampton city', 'Hancock County', 'Hand County', 'Hanover County', 'Hansford County', 'Hanson County', 'Haralson County', 'Hardee County', 'Hardeman County', 'Hardin County', 'Harding County', 'Hardy County', 'Harford County', 'Harlan County', 'Harmon County', 'Harnett County', 'Harney County', 'Harper County', 'Harris County', 'Harrison County', 'Harrisonburg city', 'Hart County', 'Hartford County', 'Hartley County', 'Harvey County', 'Haskell County', 'Hawaii', 'Hawaii County', 'Hawkins County', 'Hayes County', 'Hays County', 'Haywood County', 'Heard County', 'Hemphill County', 'Hempstead County', 'Henderson County', 'Hendricks County', 'Hendry County', 'Hennepin County', 'Henrico County', 'Henry County', 'Herkimer County', 'Hernando County', 'Hertford County', 'Hettinger County', 'Hickman County', 'Hickory County', 'Hidalgo County', 'Highland County', 'Highlands County', 'Hill County', 'Hillsborough County', 'Hillsdale County', 'Hinds County', 'Hinsdale County', 'Hitchcock County', 'Hocking County', 'Hockley County', 'Hodgeman County', 'Hoke County', 'Holmes County', 'Holt County', 'Honolulu County', 'Hood County', 'Hood River County', 'Hooker County', 'Hoonah-Angoon Census Area', 'Hopewell city', 'Hopkins County', 'Horry County', 'Hot Spring County', 'Hot Springs County', 'Houghton County', 'Houston County', 'Howard County', 'Howell County', 'Hubbard County', 'Hudson County', 'Hudspeth County', 'Huerfano County', 'Hughes County', 'Humboldt County', 'Humphreys County', 'Hunt County', 'Hunterdon County', 'Huntingdon County', 'Huntington County', 'Huron County', 'Hutchinson County', 'Hyde County', 'Iberia Parish', 'Iberville Parish', 'Ida County', 'Idaho', 'Idaho County', 'Illinois', 'Imperial County', 'Independence County', 'Indian River County', 'Indiana', 'Indiana County', 'Ingham County', 'Inyo County', 'Ionia County', 'Iosco County', 'Iowa', 'Iowa County', 'Iredell County', 'Irion County', 'Iron County', 'Iroquois County', 'Irwin County', 'Isabella County', 'Isanti County', 'Island County', 'Isle of Wight County', 'Issaquena County', 'Itasca County', 'Itawamba County', 'Izard County', 'Jack County', 'Jackson County', 'Jackson Parish', 'James City County', 'Jasper County', 'Jay County', 'Jeff Davis County', 'Jefferson County', 'Jefferson Davis County', 'Jefferson Davis Parish', 'Jefferson Parish', 'Jenkins County', 'Jennings County', 'Jerauld County', 'Jerome County', 'Jersey County', 'Jessamine County', 'Jewell County', 'Jim Hogg County', 'Jim Wells County', 'Jo Daviess County', 'Johnson County', 'Johnston County', 'Jones County', 'Josephine County', 'Juab County', 'Judith Basin County', 'Juneau City and Borough', 'Juneau County', 'Juniata County', 'Kalamazoo County', 'Kalawao County', 'Kalkaska County', 'Kanabec County', 'Kanawha County', 'Kandiyohi County', 'Kane County', 'Kankakee County', 'Kansas', 'Karnes County', 'Kauai County', 'Kaufman County', 'Kay County', 'Kearney County', 'Kearny County', 'Keith County', 'Kemper County', 'Kenai Peninsula Borough', 'Kendall County', 'Kenedy County', 'Kennebec County', 'Kenosha County', 'Kent County', 'Kenton County', 'Kentucky', 'Keokuk County', 'Kern County', 'Kerr County', 'Kershaw County', 'Ketchikan Gateway Borough', 'Kewaunee County', 'Keweenaw County', 'Keya Paha County', 'Kidder County', 'Kimball County', 'Kimble County', 'King County', 'King George County', 'King William County', 'King and Queen County', 'Kingfisher County', 'Kingman County', 'Kings County', 'Kingsbury County', 'Kinney County', 'Kiowa County', 'Kit Carson County', 'Kitsap County', 'Kittitas County', 'Kittson County', 'Klamath County', 'Kleberg County', 'Klickitat County', 'Knott County', 'Knox County', 'Kodiak Island Borough', 'Koochiching County', 'Kootenai County', 'Kosciusko County', 'Kossuth County', 'Kusilvak Census Area', 'La Crosse County', 'La Paz County', 'La Plata County', 'La Salle County', 'LaGrange County', 'LaMoure County', 'LaPorte County', 'LaSalle County', 'LaSalle Parish', 'Labette County', 'Lac qui Parle County', 'Lackawanna County', 'Laclede County', 'Lafayette County', 'Lafayette Parish', 'Lafourche Parish', 'Lake County', 'Lake and Peninsula Borough', 'Lake of the Woods County', 'Lamar County', 'Lamb County', 'Lamoille County', 'Lampasas County', 'Lancaster County', 'Lander County', 'Lane County', 'Langlade County', 'Lanier County', 'Lapeer County', 'Laramie County', 'Larimer County', 'Larue County', 'Las Animas County', 'Lassen County', 'Latah County', 'Latimer County', 'Lauderdale County', 'Laurel County', 'Laurens County', 'Lavaca County', 'Lawrence County', 'Le Flore County', 'Le Sueur County', 'Lea County', 'Leake County', 'Leavenworth County', 'Lebanon County', 'Lee County', 'Leelanau County', 'Leflore County', 'Lehigh County', 'Lemhi County', 'Lenawee County', 'Lenoir County', 'Leon County', 'Leslie County', 'Letcher County', 'Levy County', 'Lewis County', 'Lewis and Clark County', 'Lexington County', 'Lexington city', 'Liberty County', 'Licking County', 'Limestone County', 'Lincoln County', 'Lincoln Parish', 'Linn County', 'Lipscomb County', 'Litchfield County', 'Little River County', 'Live Oak County', 'Livingston County', 'Livingston Parish', 'Llano County', 'Logan County', 'Long County', 'Lonoke County', 'Lorain County', 'Los Alamos County', 'Los Angeles County', 'Loudon County', 'Loudoun County', 'Louisa County', 'Louisiana', 'Loup County', 'Love County', 'Loving County', 'Lowndes County', 'Lubbock County', 'Lucas County', 'Luce County', 'Lumpkin County', 'Luna County', 'Lunenburg County', 'Luzerne County', 'Lycoming County', 'Lyman County', 'Lynchburg city', 'Lynn County', 'Lyon County', 'Mackinac County', 'Macomb County', 'Macon County', 'Macoupin County', 'Madera County', 'Madison County', 'Madison Parish', 'Magoffin County', 'Mahaska County', 'Mahnomen County', 'Mahoning County', 'Maine', 'Major County', 'Malheur County', 'Manassas Park city', 'Manassas city', 'Manatee County', 'Manistee County', 'Manitowoc County', 'Marathon County', 'Marengo County', 'Maricopa County', 'Maries County', 'Marin County', 'Marinette County', 'Marion County', 'Mariposa County', 'Marlboro County', 'Marquette County', 'Marshall County', 'Mart

In [9]:
def answer_six():
    return "YOUR ANSWER HERE"

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [10]:
def answer_seven():
    return "YOUR ANSWER HERE"

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [11]:
def answer_eight():
    return "YOUR ANSWER HERE"